/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Access rule can perform one of the following actions: "allow" | "block".
 */
export type AccessPolicyIpAccessRuleAction = "allow" | "block";

export const AccessPolicyIpAccessRuleAction = {
    Allow: "allow",
    Block: "block",
} as const;
