/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates whether the account is presently used/usable or not.
 */
export type AccountStatus = "active" | "inactive" | "entered-in-error" | "on-hold" | "unknown";

export const AccountStatus = {
    Active: "active",
    Inactive: "inactive",
    EnteredInError: "entered-in-error",
    OnHold: "on-hold",
    Unknown: "unknown",
} as const;
