/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the agent.
 */
export type AgentStatus = "active" | "off" | "error";

export const AgentStatus = {
    Active: "active",
    Off: "off",
    Error: "error",
} as const;
