/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Estimate of the potential clinical harm, or seriousness, of the reaction to the identified substance.
 */
export type AllergyIntoleranceCriticality = "low" | "high" | "unable-to-assess";

export const AllergyIntoleranceCriticality = {
    Low: "low",
    High: "high",
    UnableToAssess: "unable-to-assess",
} as const;
