/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The overall status of the Appointment. Each of the participants has their own participation status which indicates their involvement in the process, however this status indicates the shared status.
 */
export type AppointmentStatus =
    | "proposed"
    | "pending"
    | "booked"
    | "arrived"
    | "fulfilled"
    | "cancelled"
    | "noshow"
    | "entered-in-error"
    | "checked-in"
    | "waitlist";

export const AppointmentStatus = {
    Proposed: "proposed",
    Pending: "pending",
    Booked: "booked",
    Arrived: "arrived",
    Fulfilled: "fulfilled",
    Cancelled: "cancelled",
    Noshow: "noshow",
    EnteredInError: "entered-in-error",
    CheckedIn: "checked-in",
    Waitlist: "waitlist",
} as const;
