/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An identifier for the type of network access point that originated the audit event.
 */
export type AuditEventNetworkType = "1" | "2" | "3" | "4" | "5";

export const AuditEventNetworkType = {
    One: "1",
    Two: "2",
    Three: "3",
    Four: "4",
    Five: "5",
} as const;
