/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicator for type of action performed during the event that generated the audit.
 */
export type AuditEventAction = "C" | "R" | "U" | "D" | "E";

export const AuditEventAction = {
    C: "C",
    R: "R",
    U: "U",
    D: "D",
    E: "E",
} as const;
