/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates whether the event succeeded or failed.
 */
export type AuditEventOutcome = "0" | "4" | "8" | "12";

export const AuditEventOutcome = {
    Zero: "0",
    Four: "4",
    Eight: "8",
    Twelve: "12",
} as const;
