/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A material substance originating from a biological entity intended to be transplanted or infused into another (possibly the same) biological entity.
 */
export interface BiologicallyDerivedProduct extends Metriport.fhir.BaseResource {
    resourceType: "BiologicallyDerivedProduct";
    /** This records identifiers associated with this biologically derived product instance that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropriate (e.g. in CDA documents, or in written / printed documentation). */
    identifier?: Metriport.fhir.Identifier[];
    /** Broad category of this product. */
    productCategory?: Metriport.fhir.BiologicallyDerivedProductProductCategory;
    /** A code that identifies the kind of this biologically derived product (SNOMED Ctcode). */
    productCode?: Metriport.fhir.CodeableConcept;
    /** Whether the product is currently available. */
    status?: Metriport.fhir.BiologicallyDerivedProductStatus;
    /** Procedure request to obtain this biologically derived product. */
    request?: Metriport.fhir.Reference[];
    /** Number of discrete units within this product. */
    quantity?: number;
    /** Parent product (if any). */
    parent?: Metriport.fhir.Reference[];
    /** How this product was collected. */
    collection?: Metriport.fhir.BiologicallyDerivedProductCollection;
    /** Any processing of the product during collection that does not change the fundamental nature of the product. For example adding anti-coagulants during the collection of Peripheral Blood Stem Cells. */
    processing?: Metriport.fhir.BiologicallyDerivedProductProcessing[];
    /** Any manipulation of product post-collection that is intended to alter the product. For example a buffy-coat enrichment or CD8 reduction of Peripheral Blood Stem Cells to make it more suitable for infusion. */
    manipulation?: Metriport.fhir.BiologicallyDerivedProductManipulation;
    /** Product storage. */
    storage?: Metriport.fhir.BiologicallyDerivedProductStorage[];
}
