/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Temperature scale used.
 */
export type BiologicallyDerivedProductStorageScale = "farenheit" | "celsius" | "kelvin";

export const BiologicallyDerivedProductStorageScale = {
    Farenheit: "farenheit",
    Celsius: "celsius",
    Kelvin: "kelvin",
} as const;
