/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether the product is currently available.
 */
export type BiologicallyDerivedProductStatus = "available" | "unavailable";

export const BiologicallyDerivedProductStatus = {
    Available: "available",
    Unavailable: "unavailable",
} as const;
