/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Record details about an anatomical structure. This resource may be used when a coded concept does not provide the necessary detail needed for the use case.
 */
export interface BodyStructure extends Metriport.fhir.BaseResource {
    resourceType: "BodyStructure";
    /** Identifier for this instance of the anatomical structure. */
    identifier?: Metriport.fhir.Identifier[];
    /** Whether this body site is in active use. */
    active?: boolean;
    /** The kind of structure being represented by the body structure at `BodyStructure.location`. This can define both normal and abnormal morphologies. */
    morphology?: Metriport.fhir.CodeableConcept;
    /** The anatomical location or region of the specimen, lesion, or body structure. */
    location?: Metriport.fhir.CodeableConcept;
    /** Qualifier to refine the anatomical location. These include qualifiers for laterality, relative location, directionality, number, and plane. */
    locationQualifier?: Metriport.fhir.CodeableConcept[];
    /** A summary, characterization or explanation of the body structure. */
    description?: string;
    /** Image or images used to identify a location. */
    image?: Metriport.fhir.Attachment[];
    /** The person to which the body site belongs. */
    patient: Metriport.fhir.Reference;
}
