/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Criteria for creating an AuditEvent as a result of the bot invocation. Possible values are 'always', 'never', 'on-error', or 'on-output'. Default value is 'always'.
 */
export type BotAuditEventTrigger = "always" | "never" | "on-error" | "on-output";

export const BotAuditEventTrigger = {
    Always: "always",
    Never: "never",
    OnError: "on-error",
    OnOutput: "on-output",
} as const;
