/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * User specific configuration for the Medplum application.
 */
export interface BulkDataExport {
    resourceType: "BulkDataExport";
    /** The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes. */
    id?: Metriport.fhir.Id;
    /** The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource. */
    meta?: Metriport.fhir.Meta;
    /** A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc. */
    implicitRules?: Metriport.fhir.Uri;
    /** The base language in which the resource is written. */
    language?: Metriport.fhir.Code;
    /** The status of the request. */
    status: Metriport.fhir.BulkDataExportStatus;
    /** Indicates the server's time when the query is requested. */
    requestTime: Metriport.fhir.Instant;
    /** Indicates the server's time when the query is run. The response SHOULD NOT include any resources modified after this instant, and SHALL include any matching resources modified up to and including this instant. */
    transactionTime?: Metriport.fhir.Instant;
    /** The full URL of the original Bulk Data kick-off request. In the case of a POST request, this URL will not include the request parameters. */
    request: Metriport.fhir.Uri;
    /** Indicates whether downloading the generated files requires the same authorization mechanism as the $export operation itself. */
    requiresAccessToken?: boolean;
    /** An array of file items with one entry for each generated file. If no resources are returned from the kick-off request, the server SHOULD return an empty array. */
    output?: Metriport.fhir.BulkDataExportOutput[];
    /** An array of deleted file items following the same structure as the output array. */
    deleted?: Metriport.fhir.BulkDataExportDeleted[];
    /** Array of message file items following the same structure as the output array. */
    error?: Metriport.fhir.BulkDataExportError[];
}
