/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A code that indicates how the server supports conditional read.
 */
export type CapabilityStatementResourceConditionalRead =
    | "not-supported"
    | "modified-since"
    | "not-match"
    | "full-support";

export const CapabilityStatementResourceConditionalRead = {
    NotSupported: "not-supported",
    ModifiedSince: "modified-since",
    NotMatch: "not-match",
    FullSupport: "full-support",
} as const;
