/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A coded identifier of the operation, supported by the system.
 */
export type CapabilityStatementInteraction1Code = "transaction" | "batch" | "search-system" | "history-system";

export const CapabilityStatementInteraction1Code = {
    Transaction: "transaction",
    Batch: "batch",
    SearchSystem: "search-system",
    HistorySystem: "history-system",
} as const;
