/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The mode of this event declaration - whether application is sender or receiver.
 */
export type CapabilityStatementSupportedMessageMode = "sender" | "receiver";

export const CapabilityStatementSupportedMessageMode = {
    Sender: "sender",
    Receiver: "receiver",
} as const;
