/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of this capability statement. Enables tracking the life-cycle of the content.
 */
export type CapabilityStatementStatus = "draft" | "active" | "retired" | "unknown";

export const CapabilityStatementStatus = {
    Draft: "draft",
    Active: "active",
    Retired: "retired",
    Unknown: "unknown",
} as const;
