/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * The Care Team includes all the people and organizations who plan to participate in the coordination and delivery of care for a patient.
 */
export interface CareTeam extends Metriport.fhir.BaseResource {
    resourceType: "CareTeam";
    /** Business identifiers assigned to this care team by the performer or other systems which remain constant as the resource is updated and propagates from server to server. */
    identifier?: Metriport.fhir.Identifier[];
    /** Indicates the current state of the care team. */
    status?: Metriport.fhir.CareTeamStatus;
    /** Identifies what kind of team. This is to support differentiation between multiple co-existing teams, such as care plan team, episode of care team, longitudinal care team. */
    category?: Metriport.fhir.CodeableConcept[];
    /** A label for human use intended to distinguish like teams. E.g. the "red" vs. "green" trauma teams. */
    name?: string;
    /** Identifies the patient or group whose intended care is handled by the team. */
    subject?: Metriport.fhir.Reference;
    /** The Encounter during which this CareTeam was created or to which the creation of this record is tightly associated. */
    encounter?: Metriport.fhir.Reference;
    /** Indicates when the team did (or is intended to) come into effect and end. */
    period?: Metriport.fhir.Period;
    /** Identifies all people and organizations who are expected to be involved in the care team. */
    participant?: Metriport.fhir.CareTeamParticipant[];
    /** Describes why the care team exists. */
    reasonCode?: Metriport.fhir.CodeableConcept[];
    /** Condition(s) that this care team addresses. */
    reasonReference?: Metriport.fhir.Reference[];
    /** The organization responsible for the care team. */
    managingOrganization?: Metriport.fhir.Reference[];
    /** A central contact detail for the care team (that applies to all members). */
    telecom?: Metriport.fhir.ContactPoint[];
    /** Comments made about the CareTeam. */
    note?: Metriport.fhir.Annotation[];
}
