/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Describes the intention of how one or more practitioners intend to deliver care for a particular patient, group or community for a period of time, possibly limited to care for a specific condition or set of conditions.
 */
export interface CarePlan extends Metriport.fhir.BaseResource {
    resourceType: "CarePlan";
    /** Business identifiers assigned to this care plan by the performer or other systems which remain constant as the resource is updated and propagates from server to server. */
    identifier?: Metriport.fhir.Identifier[];
    /** The URL pointing to a FHIR-defined protocol, guideline, questionnaire or other definition that is adhered to in whole or in part by this CarePlan. */
    instantiatesCanonical?: Metriport.fhir.Canonical[];
    /** The URL pointing to an externally maintained protocol, guideline, questionnaire or other definition that is adhered to in whole or in part by this CarePlan. */
    instantiatesUri?: Metriport.fhir.Uri[];
    /** A care plan that is fulfilled in whole or in part by this care plan. */
    basedOn?: Metriport.fhir.Reference[];
    /** Completed or terminated care plan whose function is taken by this new care plan. */
    replaces?: Metriport.fhir.Reference[];
    /** A larger care plan of which this particular care plan is a component or step. */
    partOf?: Metriport.fhir.Reference[];
    /** Indicates whether the plan is currently being acted upon, represents future intentions or is now a historical record. */
    status?: Metriport.fhir.Code;
    /** Indicates the level of authority/intentionality associated with the care plan and where the care plan fits into the workflow chain. */
    intent?: Metriport.fhir.Code;
    /** Identifies what "kind" of plan this is to support differentiation between multiple co-existing plans; e.g. "Home health", "psychiatric", "asthma", "disease management", "wellness plan", etc. */
    category?: Metriport.fhir.CodeableConcept[];
    /** Human-friendly name for the care plan. */
    title?: string;
    /** A description of the scope and nature of the plan. */
    description?: string;
    /** Identifies the patient or group whose intended care is described by the plan. */
    subject: Metriport.fhir.Reference;
    /** The Encounter during which this CarePlan was created or to which the creation of this record is tightly associated. */
    encounter?: Metriport.fhir.Reference;
    /** Indicates when the plan did (or is intended to) come into effect and end. */
    period?: Metriport.fhir.Period;
    /** Represents when this particular CarePlan record was created in the system, which is often a system-generated date. */
    created?: Metriport.fhir.DateTime;
    /** When populated, the author is responsible for the care plan. The care plan is attributed to the author. */
    author?: Metriport.fhir.Reference;
    /** Identifies the individual(s) or organization who provided the contents of the care plan. */
    contributor?: Metriport.fhir.Reference[];
    /** Identifies all people and organizations who are expected to be involved in the care envisioned by this plan. */
    careTeam?: Metriport.fhir.Reference[];
    /** Identifies the conditions/problems/concerns/diagnoses/etc. whose management and/or mitigation are handled by this plan. */
    addresses?: Metriport.fhir.Reference[];
    /** Identifies portions of the patient's record that specifically influenced the formation of the plan. These might include comorbidities, recent procedures, limitations, recent assessments, etc. */
    supportingInfo?: Metriport.fhir.Reference[];
    /** Describes the intended objective(s) of carrying out the care plan. */
    goal?: Metriport.fhir.Reference[];
    /** Identifies a planned action to occur as part of the plan. For example, a medication to be used, lab tests to perform, self-monitoring, education, etc. */
    activity?: Metriport.fhir.CarePlanActivity[];
    /** General notes about the care plan not covered elsewhere. */
    note?: Metriport.fhir.Annotation[];
}
