/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Used to support catalog exchange even for unsupported products, e.g. getting list of medications even if not prescribable.
 */
export type CatalogEntryStatus = "draft" | "active" | "retired" | "unknown";

export const CatalogEntryStatus = {
    Draft: "draft",
    Active: "active",
    Retired: "retired",
    Unknown: "unknown",
} as const;
