/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * The resource ChargeItem describes the provision of healthcare provider products for a certain patient, therefore referring not only to the product, but containing in addition details of the provision, like date, time, amounts and participating organizations and persons. Main Usage of the ChargeItem is to enable the billing process and internal cost allocation.
 */
export interface ChargeItem extends Metriport.fhir.BaseResource {
    resourceType: "ChargeItem";
    /** Identifiers assigned to this event performer or other systems. */
    identifier?: Metriport.fhir.Identifier[];
    /** References the (external) source of pricing information, rules of application for the code this ChargeItem uses. */
    definitionUri?: Metriport.fhir.Uri[];
    /** References the source of pricing information, rules of application for the code this ChargeItem uses. */
    definitionCanonical?: Metriport.fhir.Canonical[];
    /** The current state of the ChargeItem. */
    status?: Metriport.fhir.ChargeItemStatus;
    /** ChargeItems can be grouped to larger ChargeItems covering the whole set. */
    partOf?: Metriport.fhir.Reference[];
    /** A code that identifies the charge, like a billing code. */
    code: Metriport.fhir.CodeableConcept;
    /** The individual or set of individuals the action is being or was performed on. */
    subject: Metriport.fhir.Reference;
    /** The encounter or episode of care that establishes the context for this event. */
    context?: Metriport.fhir.Reference;
    /** Date/time(s) or duration when the charged service was applied. */
    occurrenceDateTime?: string;
    /** Date/time(s) or duration when the charged service was applied. */
    occurrencePeriod?: Metriport.fhir.Period;
    /** Date/time(s) or duration when the charged service was applied. */
    occurrenceTiming?: Metriport.fhir.Timing;
    /** Indicates who or what performed or participated in the charged service. */
    performer?: Metriport.fhir.ChargeItemPerformer[];
    /** The organization requesting the service. */
    performingOrganization?: Metriport.fhir.Reference;
    /** The organization performing the service. */
    requestingOrganization?: Metriport.fhir.Reference;
    /** The financial cost center permits the tracking of charge attribution. */
    costCenter?: Metriport.fhir.Reference;
    /** Quantity of which the charge item has been serviced. */
    quantity?: Metriport.fhir.Quantity;
    /** The anatomical location where the related service has been applied. */
    bodysite?: Metriport.fhir.CodeableConcept[];
    /** Factor overriding the factor determined by the rules associated with the code. */
    factorOverride?: Metriport.fhir.Decimal;
    /** Total price of the charge overriding the list price associated with the code. */
    priceOverride?: Metriport.fhir.Money;
    /** If the list price or the rule-based factor associated with the code is overridden, this attribute can capture a text to indicate the reason for this action. */
    overrideReason?: string;
    /** The device, practitioner, etc. who entered the charge item. */
    enterer?: Metriport.fhir.Reference;
    /** Date the charge item was entered. */
    enteredDate?: Metriport.fhir.DateTime;
    /** Describes why the event occurred in coded or textual form. */
    reason?: Metriport.fhir.CodeableConcept[];
    /** Indicated the rendered service that caused this charge. */
    service?: Metriport.fhir.Reference[];
    /** Identifies the device, food, drug or other product being charged either by type code or reference to an instance. */
    productReference?: Metriport.fhir.Reference;
    /** Identifies the device, food, drug or other product being charged either by type code or reference to an instance. */
    productCodeableConcept?: Metriport.fhir.CodeableConcept;
    /** Account into which this ChargeItems belongs. */
    account?: Metriport.fhir.Reference[];
    /** Comments made about the event by the performer, subject or other participants. */
    note?: Metriport.fhir.Annotation[];
    /** Further information supporting this charge. */
    supportingInformation?: Metriport.fhir.Reference[];
}
