/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * This resource provides the adjudication details from the processing of a Claim resource.
 */
export interface ClaimResponse extends Metriport.fhir.BaseResource {
    resourceType: "ClaimResponse";
    /** A unique identifier assigned to this claim response. */
    identifier?: Metriport.fhir.Identifier[];
    /** The status of the resource instance. */
    status?: Metriport.fhir.Code;
    /** A finer grained suite of claim type codes which may convey additional information such as Inpatient vs Outpatient and/or a specialty service. */
    type: Metriport.fhir.CodeableConcept;
    /** A finer grained suite of claim type codes which may convey additional information such as Inpatient vs Outpatient and/or a specialty service. */
    subType?: Metriport.fhir.CodeableConcept;
    /** A code to indicate whether the nature of the request is: to request adjudication of products and services previously rendered; or requesting authorization and adjudication for provision in the future; or requesting the non-binding adjudication of the listed products and services which could be provided in the future. */
    use?: Metriport.fhir.Code;
    /** The party to whom the professional services and/or products have been supplied or are being considered and for whom actual for facast reimbursement is sought. */
    patient: Metriport.fhir.Reference;
    /** The date this resource was created. */
    created?: Metriport.fhir.DateTime;
    /** The party responsible for authorization, adjudication and reimbursement. */
    insurer: Metriport.fhir.Reference;
    /** The provider which is responsible for the claim, predetermination or preauthorization. */
    requestor?: Metriport.fhir.Reference;
    /** Original request resource reference. */
    request?: Metriport.fhir.Reference;
    /** The outcome of the claim, predetermination, or preauthorization processing. */
    outcome?: Metriport.fhir.Code;
    /** A human readable description of the status of the adjudication. */
    disposition?: string;
    /** Reference from the Insurer which is used in later communications which refers to this adjudication. */
    preAuthRef?: string;
    /** The time frame during which this authorization is effective. */
    preAuthPeriod?: Metriport.fhir.Period;
    /** Type of Party to be reimbursed: subscriber, provider, other. */
    payeeType?: Metriport.fhir.CodeableConcept;
    /** A claim line. Either a simple (a product or service) or a 'group' of details which can also be a simple items or groups of sub-details. */
    item?: Metriport.fhir.ClaimResponseItem[];
    /** The first-tier service adjudications for payor added product or service lines. */
    addItem?: Metriport.fhir.ClaimResponseAddItem[];
    /** The adjudication results which are presented at the header level rather than at the line-item or add-item levels. */
    adjudication?: Metriport.fhir.ClaimResponseAdjudication[];
    /** Categorized monetary totals for the adjudication. */
    total?: Metriport.fhir.ClaimResponseTotal[];
    /** Payment details for the adjudication of the claim. */
    payment?: Metriport.fhir.ClaimResponsePayment;
    /** A code, used only on a response to a preauthorization, to indicate whether the benefits payable have been reserved and for whom. */
    fundsReserve?: Metriport.fhir.CodeableConcept;
    /** A code for the form to be used for printing the content. */
    formCode?: Metriport.fhir.CodeableConcept;
    /** The actual form, by reference or inclusion, for printing the content or an EOB. */
    form?: Metriport.fhir.Attachment;
    /** A note that describes or explains adjudication results in a human readable form. */
    processNote?: Metriport.fhir.ClaimResponseProcessNote[];
    /** Request for additional supporting or authorizing information. */
    communicationRequest?: Metriport.fhir.Reference[];
    /** Financial instruments for reimbursement for the health care products and services specified on the claim. */
    insurance?: Metriport.fhir.ClaimResponseInsurance[];
    /** Errors encountered during the processing of the adjudication. */
    error?: Metriport.fhir.ClaimResponseError[];
}
