/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * The CodeSystem resource is used to declare the existence of and describe a code system or code system supplement and its key properties, and optionally define a part or all of its content.
 */
export interface CodeSystem extends Metriport.fhir.BaseResource {
    resourceType: "CodeSystem";
    /** An absolute URI that is used to identify this code system when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which at which an authoritative instance of this code system is (or will be) published. This URL can be the target of a canonical reference. It SHALL remain the same when the code system is stored on different servers. This is used in [Coding](datatypes.html#Coding).system. */
    url?: Metriport.fhir.Uri;
    /** A formal identifier that is used to identify this code system when it is represented in other formats, or referenced in a specification, model, design or an instance. */
    identifier?: Metriport.fhir.Identifier[];
    /** The identifier that is used to identify this version of the code system when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the code system author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence. This is used in [Coding](datatypes.html#Coding).version. */
    version?: string;
    /** A natural language name identifying the code system. This name should be usable as an identifier for the module by machine processing applications such as code generation. */
    name?: string;
    /** A short, descriptive, user-friendly title for the code system. */
    title?: string;
    /** The date (and optionally time) when the code system resource was created or revised. */
    status?: Metriport.fhir.CodeSystemStatus;
    /** A Boolean value to indicate that this code system is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage. */
    experimental?: boolean;
    /** The date (and optionally time) when the code system was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the code system changes. */
    date?: Metriport.fhir.DateTime;
    /** The name of the organization or individual that published the code system. */
    publisher?: string;
    /** Contact details to assist a user in finding and communicating with the publisher. */
    contact?: Metriport.fhir.ContactDetail[];
    /** A free text natural language description of the code system from a consumer's perspective. */
    description?: Metriport.fhir.Markdown;
    /** The content was developed with a focus and intent of supporting the contexts that are listed. These contexts may be general categories (gender, age, ...) or may be references to specific programs (insurance plans, studies, ...) and may be used to assist with indexing and searching for appropriate code system instances. */
    useContext?: Metriport.fhir.UsageContext[];
    /** A legal or geographic region in which the code system is intended to be used. */
    jurisdiction?: Metriport.fhir.CodeableConcept[];
    /** Explanation of why this code system is needed and why it has been designed as it has. */
    purpose?: Metriport.fhir.Markdown;
    /** A copyright statement relating to the code system and/or its contents. Copyright statements are generally legal restrictions on the use and publishing of the code system. */
    copyright?: Metriport.fhir.Markdown;
    /** If code comparison is case sensitive when codes within this system are compared to each other. */
    caseSensitive?: boolean;
    /** Canonical reference to the value set that contains the entire code system. */
    valueSet?: Metriport.fhir.Canonical;
    /** The meaning of the hierarchy of concepts as represented in this resource. */
    hierarchyMeaning?: Metriport.fhir.CodeSystemHierarchyMeaning;
    /** The code system defines a compositional (post-coordination) grammar. */
    compositional?: boolean;
    /** This flag is used to signify that the code system does not commit to concept permanence across versions. If true, a version must be specified when referencing this code system. */
    versionNeeded?: boolean;
    /** The extent of the content of the code system (the concepts and codes it defines) are represented in this resource instance. */
    content?: Metriport.fhir.CodeSystemContent;
    /** The canonical URL of the code system that this code system supplement is adding designations and properties to. */
    supplements?: Metriport.fhir.Canonical;
    /** The total number of concepts defined by the code system. Where the code system has a compositional grammar, the basis of this count is defined by the system steward. */
    count?: Metriport.fhir.UnsignedInt;
    /** A filter that can be used in a value set compose statement when selecting concepts using a filter. */
    filter?: Metriport.fhir.CodeSystemFilter[];
    /** A property defines an additional slot through which additional information can be provided about a concept. */
    property?: Metriport.fhir.CodeSystemProperty[];
    /** Concepts that are in the code system. The concept definitions are inherently hierarchical, but the definitions must be consulted to determine what the meanings of the hierarchical relationships are. */
    concept?: Metriport.fhir.CodeSystemConcept[];
}
