/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of the property value. Properties of type "code" contain a code defined by the code system (e.g. a reference to another defined concept).
 */
export type CodeSystemPropertyType = "code" | "Coding" | "string" | "integer" | "boolean" | "dateTime" | "decimal";

export const CodeSystemPropertyType = {
    Code: "code",
    Coding: "Coding",
    String: "string",
    Integer: "integer",
    Boolean: "boolean",
    DateTime: "dateTime",
    Decimal: "decimal",
} as const;
