/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Which compartment this definition describes.
 */
export type CompartmentDefinitionCode = "Patient" | "Encounter" | "RelatedPerson" | "Practitioner" | "Device";

export const CompartmentDefinitionCode = {
    Patient: "Patient",
    Encounter: "Encounter",
    RelatedPerson: "RelatedPerson",
    Practitioner: "Practitioner",
    Device: "Device",
} as const;
