/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The workflow/clinical status of this composition. The status is a marker for the clinical standing of the document.
 */
export type CompositionStatus = "preliminary" | "final" | "amended" | "entered-in-error";

export const CompositionStatus = {
    Preliminary: "preliminary",
    Final: "final",
    Amended: "amended",
    EnteredInError: "entered-in-error",
} as const;
