/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A clinical condition, problem, diagnosis, or other event, situation, issue, or clinical concept that has risen to a level of concern.
 */
export interface Condition extends Metriport.fhir.BaseResource {
    resourceType: "Condition";
    /** Business identifiers assigned to this condition by the performer or other systems which remain constant as the resource is updated and propagates from server to server. */
    identifier?: Metriport.fhir.Identifier[];
    /** The clinical status of the condition. */
    clinicalStatus?: Metriport.fhir.CodeableConcept;
    /** The verification status to support the clinical status of the condition. */
    verificationStatus?: Metriport.fhir.CodeableConcept;
    /** A category assigned to the condition. */
    category?: Metriport.fhir.CodeableConcept[];
    /** A subjective assessment of the severity of the condition as evaluated by the clinician. */
    severity?: Metriport.fhir.CodeableConcept;
    /** Identification of the condition, problem or diagnosis. */
    code?: Metriport.fhir.CodeableConcept;
    /** The anatomical location where this condition manifests itself. */
    bodySite?: Metriport.fhir.CodeableConcept[];
    /** Indicates the patient or group who the condition record is associated with. */
    subject: Metriport.fhir.Reference;
    /** The Encounter during which this Condition was created or to which the creation of this record is tightly associated. */
    encounter?: Metriport.fhir.Reference;
    /** Estimated or actual date or date-time the condition began, in the opinion of the clinician. */
    onsetDateTime?: string;
    /** Estimated or actual date or date-time the condition began, in the opinion of the clinician. */
    onsetAge?: Metriport.fhir.Age;
    /** Estimated or actual date or date-time the condition began, in the opinion of the clinician. */
    onsetPeriod?: Metriport.fhir.Period;
    /** Estimated or actual date or date-time the condition began, in the opinion of the clinician. */
    onsetRange?: Metriport.fhir.Range;
    /** Estimated or actual date or date-time the condition began, in the opinion of the clinician. */
    onsetString?: string;
    /** The date or estimated date that the condition resolved or went into remission. This is called "abatement" because of the many overloaded connotations associated with "remission" or "resolution" - Conditions are never really resolved, but they can abate. */
    abatementDateTime?: string;
    /** The date or estimated date that the condition resolved or went into remission. This is called "abatement" because of the many overloaded connotations associated with "remission" or "resolution" - Conditions are never really resolved, but they can abate. */
    abatementAge?: Metriport.fhir.Age;
    /** The date or estimated date that the condition resolved or went into remission. This is called "abatement" because of the many overloaded connotations associated with "remission" or "resolution" - Conditions are never really resolved, but they can abate. */
    abatementPeriod?: Metriport.fhir.Period;
    /** The date or estimated date that the condition resolved or went into remission. This is called "abatement" because of the many overloaded connotations associated with "remission" or "resolution" - Conditions are never really resolved, but they can abate. */
    abatementRange?: Metriport.fhir.Range;
    /** The date or estimated date that the condition resolved or went into remission. This is called "abatement" because of the many overloaded connotations associated with "remission" or "resolution" - Conditions are never really resolved, but they can abate. */
    abatementString?: string;
    /** The recordedDate represents when this particular Condition record was created in the system, which is often a system-generated date. */
    recordedDate?: Metriport.fhir.DateTime;
    /** Individual who recorded the record and takes responsibility for its content. */
    recorder?: Metriport.fhir.Reference;
    /** Individual who is making the condition statement. */
    asserter?: Metriport.fhir.Reference;
    /** Clinical stage or grade of a condition. May include formal severity assessments. */
    stage?: Metriport.fhir.ConditionStage[];
    /** Supporting evidence / manifestations that are the basis of the Condition's verification status, such as evidence that confirmed or refuted the condition. */
    evidence?: Metriport.fhir.ConditionEvidence[];
    /** Additional information about the Condition. This is a general notes/comments entry for description of the Condition, its diagnosis and prognosis. */
    note?: Metriport.fhir.Annotation[];
}
