/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A record of a healthcare consumer’s choices, which permits or denies identified recipient(s) or recipient role(s) to perform one or more actions within a given policy context, for specific purposes and periods of time.
 */
export interface Consent extends Metriport.fhir.BaseResource {
    resourceType: "Consent";
    /** Unique identifier for this copy of the Consent Statement. */
    identifier?: Metriport.fhir.Identifier[];
    /** Indicates the current state of this consent. */
    status?: Metriport.fhir.ConsentStatus;
    /** A selector of the type of consent being presented: ADR, Privacy, Treatment, Research. This list is now extensible. */
    scope: Metriport.fhir.CodeableConcept;
    /** A classification of the type of consents found in the statement. This element supports indexing and retrieval of consent statements. */
    category: Metriport.fhir.CodeableConcept[];
    /** The patient/healthcare consumer to whom this consent applies. */
    patient?: Metriport.fhir.Reference;
    /** When this Consent was issued / created / indexed. */
    dateTime?: Metriport.fhir.DateTime;
    /** Either the Grantor, which is the entity responsible for granting the rights listed in a Consent Directive or the Grantee, which is the entity responsible for complying with the Consent Directive, including any obligations or limitations on authorizations and enforcement of prohibitions. */
    performer?: Metriport.fhir.Reference[];
    /** The organization that manages the consent, and the framework within which it is executed. */
    organization?: Metriport.fhir.Reference[];
    /** The source on which this consent statement is based. The source might be a scanned original paper form, or a reference to a consent that links back to such a source, a reference to a document repository (e.g. XDS) that stores the original consent document. */
    sourceAttachment?: Metriport.fhir.Attachment;
    /** The source on which this consent statement is based. The source might be a scanned original paper form, or a reference to a consent that links back to such a source, a reference to a document repository (e.g. XDS) that stores the original consent document. */
    sourceReference?: Metriport.fhir.Reference;
    /** The references to the policies that are included in this consent scope. Policies may be organizational, but are often defined jurisdictionally, or in law. */
    policy?: Metriport.fhir.ConsentPolicy[];
    /** A reference to the specific base computable regulation or policy. */
    policyRule?: Metriport.fhir.CodeableConcept;
    /** Whether a treatment instruction (e.g. artificial respiration yes or no) was verified with the patient, his/her family or another authorized person. */
    verification?: Metriport.fhir.ConsentVerification[];
    /** An exception to the base policy of this consent. An exception can be an addition or removal of access permissions. */
    provision?: Metriport.fhir.ConsentProvision;
}
