/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * How the resource reference is interpreted when testing consent restrictions.
 */
export type ConsentDataMeaning = "instance" | "related" | "dependents" | "authoredby";

export const ConsentDataMeaning = {
    Instance: "instance",
    Related: "related",
    Dependents: "dependents",
    Authoredby: "authoredby",
} as const;
