/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * The CoverageEligibilityRequest provides patient and insurance coverage information to an insurer for them to respond, in the form of an CoverageEligibilityResponse, with information regarding whether the stated coverage is valid and in-force and optionally to provide the insurance details of the policy.
 */
export interface CoverageEligibilityRequest extends Metriport.fhir.BaseResource {
    resourceType: "CoverageEligibilityRequest";
    /** A unique identifier assigned to this coverage eligiblity request. */
    identifier?: Metriport.fhir.Identifier[];
    /** The status of the resource instance. */
    status?: Metriport.fhir.Code;
    /** When the requestor expects the processor to complete processing. */
    priority?: Metriport.fhir.CodeableConcept;
    /** Code to specify whether requesting: prior authorization requirements for some service categories or billing codes; benefits for coverages specified or discovered; discovery and return of coverages for the patient; and/or validation that the specified coverage is in-force at the date/period specified or 'now' if not specified. */
    purpose?: Metriport.fhir.CoverageEligibilityRequestPurposeItem[];
    /** The party who is the beneficiary of the supplied coverage and for whom eligibility is sought. */
    patient: Metriport.fhir.Reference;
    /** The date or dates when the enclosed suite of services were performed or completed. */
    servicedDate?: string;
    /** The date or dates when the enclosed suite of services were performed or completed. */
    servicedPeriod?: Metriport.fhir.Period;
    /** The date when this resource was created. */
    created?: Metriport.fhir.DateTime;
    /** Person who created the request. */
    enterer?: Metriport.fhir.Reference;
    /** The provider which is responsible for the request. */
    provider?: Metriport.fhir.Reference;
    /** The Insurer who issued the coverage in question and is the recipient of the request. */
    insurer: Metriport.fhir.Reference;
    /** Facility where the services are intended to be provided. */
    facility?: Metriport.fhir.Reference;
    /** Additional information codes regarding exceptions, special considerations, the condition, situation, prior or concurrent issues. */
    supportingInfo?: Metriport.fhir.CoverageEligibilityRequestSupportingInfo[];
    /** Financial instruments for reimbursement for the health care products and services. */
    insurance?: Metriport.fhir.CoverageEligibilityRequestInsurance[];
    /** Service categories or billable services for which benefit details and/or an authorization prior to service delivery may be required by the payor. */
    item?: Metriport.fhir.CoverageEligibilityRequestItem[];
}
