/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CoverageEligibilityRequestPurposeItem = "auth-requirements" | "benefits" | "discovery" | "validation";

export const CoverageEligibilityRequestPurposeItem = {
    AuthRequirements: "auth-requirements",
    Benefits: "benefits",
    Discovery: "discovery",
    Validation: "validation",
} as const;
