/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Financial instrument which may be used to reimburse or pay for health care products and services. Includes both insurance and self-payment.
 */
export interface Coverage extends Metriport.fhir.BaseResource {
    resourceType: "Coverage";
    /** A unique identifier assigned to this coverage. */
    identifier?: Metriport.fhir.Identifier[];
    /** The status of the resource instance. */
    status?: Metriport.fhir.Code;
    /** The type of coverage: social program, medical plan, accident coverage (workers compensation, auto), group health or payment by an individual or organization. */
    type?: Metriport.fhir.CodeableConcept;
    /** The party who 'owns' the insurance policy. */
    policyHolder?: Metriport.fhir.Reference;
    /** The party who has signed-up for or 'owns' the contractual relationship to the policy or to whom the benefit of the policy for services rendered to them or their family is due. */
    subscriber?: Metriport.fhir.Reference;
    /** The insurer assigned ID for the Subscriber. */
    subscriberId?: string;
    /** The party who benefits from the insurance coverage; the patient when products and/or services are provided. */
    beneficiary: Metriport.fhir.Reference;
    /** A unique identifier for a dependent under the coverage. */
    dependent?: string;
    /** The relationship of beneficiary (patient) to the subscriber. */
    relationship?: Metriport.fhir.CodeableConcept;
    /** Time period during which the coverage is in force. A missing start date indicates the start date isn't known, a missing end date means the coverage is continuing to be in force. */
    period?: Metriport.fhir.Period;
    /** The program or plan underwriter or payor including both insurance and non-insurance agreements, such as patient-pay agreements. */
    payor: Metriport.fhir.Reference[];
    /** A suite of underwriter specific classifiers. */
    class?: Metriport.fhir.CoverageClass[];
    /** The order of applicability of this coverage relative to other coverages which are currently in force. Note, there may be gaps in the numbering and this does not imply primary, secondary etc. as the specific positioning of coverages depends upon the episode of care. */
    order?: Metriport.fhir.PositiveInt;
    /** The insurer-specific identifier for the insurer-defined network of providers to which the beneficiary may seek treatment which will be covered at the 'in-network' rate, otherwise 'out of network' terms and conditions apply. */
    network?: string;
    /** A suite of codes indicating the cost category and associated amount which have been detailed in the policy and may have been included on the health card. */
    costToBeneficiary?: Metriport.fhir.CoverageCostToBeneficiary[];
    /** When 'subrogation=true' this insurance instance has been included not for adjudication but to provide insurers with the details to recover costs. */
    subrogation?: boolean;
    /** The policy(s) which constitute this insurance coverage. */
    contract?: Metriport.fhir.Reference[];
}
