/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The outcome of the request processing.
 */
export type CoverageEligibilityResponseOutcome = "queued" | "complete" | "error" | "partial";

export const CoverageEligibilityResponseOutcome = {
    Queued: "queued",
    Complete: "complete",
    Error: "error",
    Partial: "partial",
} as const;
