/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates the degree of importance associated with the identified issue based on the potential impact on the patient.
 */
export type DetectedIssueSeverity = "high" | "moderate" | "low";

export const DetectedIssueSeverity = {
    High: "high",
    Moderate: "moderate",
    Low: "low",
} as const;
