/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A code representing the patient or other source's judgment about the state of the device used that this statement is about. Generally this will be active or completed.
 */
export type DeviceUseStatementStatus = "active" | "completed" | "entered-in-error" | "intended" | "stopped" | "on-hold";

export const DeviceUseStatementStatus = {
    Active: "active",
    Completed: "completed",
    EnteredInError: "entered-in-error",
    Intended: "intended",
    Stopped: "stopped",
    OnHold: "on-hold",
} as const;
