/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of deviceName. UDILabelName | UserFriendlyName | PatientReportedName | ManufactureDeviceName | ModelName.
 */
export type DeviceDefinitionDeviceNameType =
    | "udi-label-name"
    | "user-friendly-name"
    | "patient-reported-name"
    | "manufacturer-name"
    | "model-name"
    | "other";

export const DeviceDefinitionDeviceNameType = {
    UdiLabelName: "udi-label-name",
    UserFriendlyName: "user-friendly-name",
    PatientReportedName: "patient-reported-name",
    ManufacturerName: "manufacturer-name",
    ModelName: "model-name",
    Other: "other",
} as const;
