/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * The characteristics, operational status and capabilities of a medical-related component of a medical device.
 */
export interface DeviceDefinition extends Metriport.fhir.BaseResource {
    resourceType: "DeviceDefinition";
    /** Unique instance identifiers assigned to a device by the software, manufacturers, other organizations or owners. For example: handle ID. */
    identifier?: Metriport.fhir.Identifier[];
    /** Unique device identifier (UDI) assigned to device label or package. Note that the Device may include multiple udiCarriers as it either may include just the udiCarrier for the jurisdiction it is sold, or for multiple jurisdictions it could have been sold. */
    udiDeviceIdentifier?: Metriport.fhir.DeviceDefinitionUdiDeviceIdentifier[];
    /** A name of the manufacturer. */
    manufacturerString?: string;
    /** A name of the manufacturer. */
    manufacturerReference?: Metriport.fhir.Reference;
    /** A name given to the device to identify it. */
    deviceName?: Metriport.fhir.DeviceDefinitionDeviceName[];
    /** The model number for the device. */
    modelNumber?: string;
    /** What kind of device or device system this is. */
    type?: Metriport.fhir.CodeableConcept;
    /** The capabilities supported on a device, the standards to which the device conforms for a particular purpose, and used for the communication. */
    specialization?: Metriport.fhir.DeviceDefinitionSpecialization[];
    /** The available versions of the device, e.g., software versions. */
    version?: string[];
    /** Safety characteristics of the device. */
    safety?: Metriport.fhir.CodeableConcept[];
    /** Shelf Life and storage information. */
    shelfLifeStorage?: Metriport.fhir.ProductShelfLife[];
    /** Dimensions, color etc. */
    physicalCharacteristics?: Metriport.fhir.ProdCharacteristic;
    /** Language code for the human-readable text strings produced by the device (all supported). */
    languageCode?: Metriport.fhir.CodeableConcept[];
    /** Device capabilities. */
    capability?: Metriport.fhir.DeviceDefinitionCapability[];
    /** The actual configuration settings of a device as it actually operates, e.g., regulation status, time properties. */
    property?: Metriport.fhir.DeviceDefinitionProperty[];
    /** An organization that is responsible for the provision and ongoing maintenance of the device. */
    owner?: Metriport.fhir.Reference;
    /** Contact details for an organization or a particular human that is responsible for the device. */
    contact?: Metriport.fhir.ContactPoint[];
    /** A network address on which the device may be contacted directly. */
    url?: Metriport.fhir.Uri;
    /** Access to on-line information about the device. */
    onlineInformation?: Metriport.fhir.Uri;
    /** Descriptive information, usage information or implantation information that is not captured in an existing element. */
    note?: Metriport.fhir.Annotation[];
    /** The quantity of the device present in the packaging (e.g. the number of devices present in a pack, or the number of devices in the same package of the medicinal product). */
    quantity?: Metriport.fhir.Quantity;
    /** The parent device it can be part of. */
    parentDevice?: Metriport.fhir.Reference;
    /** A substance used to create the material(s) of which the device is made. */
    material?: Metriport.fhir.DeviceDefinitionMaterial[];
    /** What kind of device or device system this is. */
    classification?: Metriport.fhir.DeviceDefinitionClassification[];
}
