/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A record of a device being used by a patient where the record is the result of a report from the patient or another clinician.
 */
export interface DeviceUseStatement extends Metriport.fhir.BaseResource {
    resourceType: "DeviceUseStatement";
    /** An external identifier for this statement such as an IRI. */
    identifier?: Metriport.fhir.Identifier[];
    /** A plan, proposal or order that is fulfilled in whole or in part by this DeviceUseStatement. */
    basedOn?: Metriport.fhir.Reference[];
    /** A code representing the patient or other source's judgment about the state of the device used that this statement is about. Generally this will be active or completed. */
    status?: Metriport.fhir.DeviceUseStatementStatus;
    /** The patient who used the device. */
    subject: Metriport.fhir.Reference;
    /** Allows linking the DeviceUseStatement to the underlying Request, or to other information that supports or is used to derive the DeviceUseStatement. */
    derivedFrom?: Metriport.fhir.Reference[];
    /** How often the device was used. */
    timingTiming?: Metriport.fhir.Timing;
    /** How often the device was used. */
    timingPeriod?: Metriport.fhir.Period;
    /** How often the device was used. */
    timingDateTime?: string;
    /** The time at which the statement was made/recorded. */
    recordedOn?: Metriport.fhir.DateTime;
    /** Who reported the device was being used by the patient. */
    source?: Metriport.fhir.Reference;
    /** The details of the device used. */
    device: Metriport.fhir.Reference;
    /** Reason or justification for the use of the device. */
    reasonCode?: Metriport.fhir.CodeableConcept[];
    /** Indicates another resource whose existence justifies this DeviceUseStatement. */
    reasonReference?: Metriport.fhir.Reference[];
    /** Indicates the anotomic location on the subject's body where the device was used ( i.e. the target). */
    bodySite?: Metriport.fhir.CodeableConcept;
    /** Details about the device statement that were not represented at all or sufficiently in one of the attributes provided in a class. These may include for example a comment, an instruction, or a note associated with the statement. */
    note?: Metriport.fhir.Annotation[];
}
