/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A type of a manufactured item that is used in the provision of healthcare without being substantially changed through that activity. The device may be a medical or non-medical device.
 */
export interface Device extends Metriport.fhir.BaseResource {
    resourceType: "Device";
    /** Unique instance identifiers assigned to a device by manufacturers other organizations or owners. */
    identifier?: Metriport.fhir.Identifier[];
    /** The reference to the definition for the device. */
    definition?: Metriport.fhir.Reference;
    /** Unique device identifier (UDI) assigned to device label or package. Note that the Device may include multiple udiCarriers as it either may include just the udiCarrier for the jurisdiction it is sold, or for multiple jurisdictions it could have been sold. */
    udiCarrier?: Metriport.fhir.DeviceUdiCarrier[];
    /** Status of the Device availability. */
    status?: Metriport.fhir.DeviceStatus;
    /** Reason for the dtatus of the Device availability. */
    statusReason?: Metriport.fhir.CodeableConcept[];
    /** The distinct identification string as required by regulation for a human cell, tissue, or cellular and tissue-based product. */
    distinctIdentifier?: string;
    /** A name of the manufacturer. */
    manufacturer?: string;
    /** The date and time when the device was manufactured. */
    manufactureDate?: Metriport.fhir.DateTime;
    /** The date and time beyond which this device is no longer valid or should not be used (if applicable). */
    expirationDate?: Metriport.fhir.DateTime;
    /** Lot number assigned by the manufacturer. */
    lotNumber?: string;
    /** The serial number assigned by the organization when the device was manufactured. */
    serialNumber?: string;
    /** This represents the manufacturer's name of the device as provided by the device, from a UDI label, or by a person describing the Device. This typically would be used when a person provides the name(s) or when the device represents one of the names available from DeviceDefinition. */
    deviceName?: Metriport.fhir.DeviceDeviceName[];
    /** The model number for the device. */
    modelNumber?: string;
    /** The part number of the device. */
    partNumber?: string;
    /** The kind or type of device. */
    type?: Metriport.fhir.CodeableConcept;
    /** The capabilities supported on a device, the standards to which the device conforms for a particular purpose, and used for the communication. */
    specialization?: Metriport.fhir.DeviceSpecialization[];
    /** The actual design of the device or software version running on the device. */
    version?: Metriport.fhir.DeviceVersion[];
    /** The actual configuration settings of a device as it actually operates, e.g., regulation status, time properties. */
    property?: Metriport.fhir.DeviceProperty[];
    /** Patient information, If the device is affixed to a person. */
    patient?: Metriport.fhir.Reference;
    /** An organization that is responsible for the provision and ongoing maintenance of the device. */
    owner?: Metriport.fhir.Reference;
    /** Contact details for an organization or a particular human that is responsible for the device. */
    contact?: Metriport.fhir.ContactPoint[];
    /** The place where the device can be found. */
    location?: Metriport.fhir.Reference;
    /** A network address on which the device may be contacted directly. */
    url?: Metriport.fhir.Uri;
    /** Descriptive information, usage information or implantation information that is not captured in an existing element. */
    note?: Metriport.fhir.Annotation[];
    /** Provides additional safety characteristics about a medical device. For example devices containing latex. */
    safety?: Metriport.fhir.CodeableConcept[];
    /** The parent device. */
    parent?: Metriport.fhir.Reference;
}
