/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates current operational state of the device. For example: On, Off, Standby, etc.
 */
export type DeviceMetricOperationalStatus = "on" | "off" | "standby" | "entered-in-error";

export const DeviceMetricOperationalStatus = {
    On: "on",
    Off: "off",
    Standby: "standby",
    EnteredInError: "entered-in-error",
} as const;
