/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of this document reference.
 */
export type DocumentReferenceStatus = "current" | "superseded" | "entered-in-error";

export const DocumentReferenceStatus = {
    Current: "current",
    Superseded: "superseded",
    EnteredInError: "entered-in-error",
} as const;
