/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A collection of documents compiled for a purpose together with metadata that applies to the collection.
 */
export interface DocumentManifest extends Metriport.fhir.BaseResource {
    resourceType: "DocumentManifest";
    /** A single identifier that uniquely identifies this manifest. Principally used to refer to the manifest in non-FHIR contexts. */
    masterIdentifier?: Metriport.fhir.Identifier;
    /** Other identifiers associated with the document manifest, including version independent identifiers. */
    identifier?: Metriport.fhir.Identifier[];
    /** The status of this document manifest. */
    status?: Metriport.fhir.DocumentManifestStatus;
    /** The code specifying the type of clinical activity that resulted in placing the associated content into the DocumentManifest. */
    type?: Metriport.fhir.CodeableConcept;
    /** Who or what the set of documents is about. The documents can be about a person, (patient or healthcare practitioner), a device (i.e. machine) or even a group of subjects (such as a document about a herd of farm animals, or a set of patients that share a common exposure). If the documents cross more than one subject, then more than one subject is allowed here (unusual use case). */
    subject?: Metriport.fhir.Reference;
    /** When the document manifest was created for submission to the server (not necessarily the same thing as the actual resource last modified time, since it may be modified, replicated, etc.). */
    created?: Metriport.fhir.DateTime;
    /** Identifies who is the author of the manifest. Manifest author is not necessarly the author of the references included. */
    author?: Metriport.fhir.Reference[];
    /** A patient, practitioner, or organization for which this set of documents is intended. */
    recipient?: Metriport.fhir.Reference[];
    /** Identifies the source system, application, or software that produced the document manifest. */
    source?: Metriport.fhir.Uri;
    /** Human-readable description of the source document. This is sometimes known as the "title". */
    description?: string;
    /** The list of Resources that consist of the parts of this manifest. */
    content: Metriport.fhir.Reference[];
    /** Related identifiers or resources associated with the DocumentManifest. */
    related?: Metriport.fhir.DocumentManifestRelated[];
}
