/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A reference to a document of any kind for any purpose. Provides metadata about the document so that the document can be discovered and managed. The scope of a document is any seralized object with a mime-type, so includes formal patient centric documents (CDA), cliical notes, scanned paper, and non-patient specific documents like policy text.
 */
export interface DocumentReference extends Metriport.fhir.BaseResource {
    resourceType: "DocumentReference";
    /** Document identifier as assigned by the source of the document. This identifier is specific to this version of the document. This unique identifier may be used elsewhere to identify this version of the document. */
    masterIdentifier?: Metriport.fhir.Identifier;
    /** Other identifiers associated with the document, including version independent identifiers. */
    identifier?: Metriport.fhir.Identifier[];
    /** The status of this document reference. */
    status?: Metriport.fhir.DocumentReferenceStatus;
    /** The status of the underlying document. */
    docStatus?: Metriport.fhir.Code;
    /** Specifies the particular kind of document referenced (e.g. History and Physical, Discharge Summary, Progress Note). This usually equates to the purpose of making the document referenced. */
    type?: Metriport.fhir.CodeableConcept;
    /** A categorization for the type of document referenced - helps for indexing and searching. This may be implied by or derived from the code specified in the DocumentReference.type. */
    category?: Metriport.fhir.CodeableConcept[];
    /** Who or what the document is about. The document can be about a person, (patient or healthcare practitioner), a device (e.g. a machine) or even a group of subjects (such as a document about a herd of farm animals, or a set of patients that share a common exposure). */
    subject?: Metriport.fhir.Reference;
    /** When the document reference was created. */
    date?: Metriport.fhir.Instant;
    /** Identifies who is responsible for adding the information to the document. */
    author?: Metriport.fhir.Reference[];
    /** Which person or organization authenticates that this document is valid. */
    authenticator?: Metriport.fhir.Reference;
    /** Identifies the organization or group who is responsible for ongoing maintenance of and access to the document. */
    custodian?: Metriport.fhir.Reference;
    /** Relationships that this document has with other document references that already exist. */
    relatesTo?: Metriport.fhir.DocumentReferenceRelatesTo[];
    /** Human-readable description of the source document. */
    description?: string;
    /** A set of Security-Tag codes specifying the level of privacy/security of the Document. Note that DocumentReference.meta.security contains the security labels of the "reference" to the document, while DocumentReference.securityLabel contains a snapshot of the security labels on the document the reference refers to. */
    securityLabel?: Metriport.fhir.CodeableConcept[];
    /** The document and format referenced. There may be multiple content element repetitions, each with a different format. */
    content: Metriport.fhir.DocumentReferenceContent[];
    /** The clinical context in which the document was prepared. */
    context?: Metriport.fhir.DocumentReferenceContext;
}
