/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Domain specific configuration for the Medplum application.
 */
export interface DomainConfiguration {
    resourceType: "DomainConfiguration";
    /** The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes. */
    id?: Metriport.fhir.Id;
    /** The metadata about the resource. This is content that is maintained by the infrastructure. Changes to the content might not always be associated with version changes to the resource. */
    meta?: Metriport.fhir.Meta;
    /** A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc. */
    implicitRules?: Metriport.fhir.Uri;
    /** The base language in which the resource is written. */
    language?: Metriport.fhir.Code;
    /** Globally unique domain name for this configuration. */
    domain: Metriport.fhir.Uri;
    /** Optional external Identity Provider (IdP) for the domain name. */
    identityProvider?: Metriport.fhir.IdentityProvider;
}
