/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether these results are for the exposure state or alternative exposure state.
 */
export type EffectEvidenceSynthesisResultsByExposureExposureState = "exposure" | "exposure-alternative";

export const EffectEvidenceSynthesisResultsByExposureExposureState = {
    Exposure: "exposure",
    ExposureAlternative: "exposure-alternative",
} as const;
