/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Identifies the impact constraint violation has on the conformance of the instance.
 */
export type ElementDefinitionConstraintSeverity = "error" | "warning";

export const ElementDefinitionConstraintSeverity = {
    Error: "error",
    Warning: "warning",
} as const;
