/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ElementDefinitionRepresentationItem = "xmlAttr" | "xmlText" | "typeAttr" | "cdaText" | "xhtml";

export const ElementDefinitionRepresentationItem = {
    XmlAttr: "xmlAttr",
    XmlText: "xmlText",
    TypeAttr: "typeAttr",
    CdaText: "cdaText",
    Xhtml: "xhtml",
} as const;
