/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Captures constraints on each element within the resource, profile, or extension.
 */
export interface ElementDefinitionExample {
    /** Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces. */
    id?: string;
    /** May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. */
    extension?: Metriport.fhir.Extension[];
    /** May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions. Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself). */
    modifierExtension?: Metriport.fhir.Extension[];
    /** Describes the purpose of this example amoung the set of examples. */
    label?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueBase64Binary?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueBoolean?: boolean;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueCanonical?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueCode?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueDate?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueDateTime?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueDecimal?: number;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueId?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueInstant?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueInteger?: number;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueMarkdown?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueOid?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valuePositiveInt?: number;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueString?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueTime?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueUnsignedInt?: number;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueUri?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueUrl?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueUuid?: string;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueAddress?: Metriport.fhir.Address;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueAge?: Metriport.fhir.Age;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueAnnotation?: Metriport.fhir.Annotation;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueAttachment?: Metriport.fhir.Attachment;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueCodeableConcept?: Metriport.fhir.CodeableConcept;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueCoding?: Metriport.fhir.Coding;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueContactPoint?: Metriport.fhir.ContactPoint;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueCount?: Metriport.fhir.Count;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueDistance?: Metriport.fhir.Distance;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueDuration?: Metriport.fhir.Duration;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueHumanName?: Metriport.fhir.HumanName;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueIdentifier?: Metriport.fhir.Identifier;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueMoney?: Metriport.fhir.Money;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valuePeriod?: Metriport.fhir.Period;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueQuantity?: Metriport.fhir.Quantity;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueRange?: Metriport.fhir.Range;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueRatio?: Metriport.fhir.Ratio;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueReference?: Metriport.fhir.Reference;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueSampledData?: Metriport.fhir.SampledData;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueSignature?: Metriport.fhir.Signature;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueTiming?: Metriport.fhir.Timing;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueContactDetail?: Metriport.fhir.ContactDetail;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueContributor?: Metriport.fhir.Contributor;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueDataRequirement?: Metriport.fhir.DataRequirement;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueExpression?: Metriport.fhir.Expression;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueParameterDefinition?: Metriport.fhir.ParameterDefinition;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueRelatedArtifact?: Metriport.fhir.RelatedArtifact;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueTriggerDefinition?: Metriport.fhir.TriggerDefinition;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueUsageContext?: Metriport.fhir.UsageContext;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueDosage?: Metriport.fhir.Dosage;
    /** The actual value for the element, which must be one of the types allowed for this element. */
    valueMeta?: Metriport.fhir.Meta;
}
