/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Whether this reference needs to be version specific or version independent, or whether either can be used.
 */
export type ElementDefinitionTypeVersioning = "either" | "independent" | "specific";

export const ElementDefinitionTypeVersioning = {
    Either: "either",
    Independent: "independent",
    Specific: "specific",
} as const;
