/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * An interaction between a patient and healthcare provider(s) for the purpose of providing healthcare service(s) or assessing the health status of a patient.
 */
export interface Encounter extends Metriport.fhir.BaseResource {
    resourceType: "Encounter";
    /** Identifier(s) by which this encounter is known. */
    identifier?: Metriport.fhir.Identifier[];
    /** planned | arrived | triaged | in-progress | onleave | finished | cancelled +. */
    status?: Metriport.fhir.EncounterStatus;
    /** The status history permits the encounter resource to contain the status history without needing to read through the historical versions of the resource, or even have the server store them. */
    statusHistory?: Metriport.fhir.EncounterStatusHistory[];
    /** Concepts representing classification of patient encounter such as ambulatory (outpatient), inpatient, emergency, home health or others due to local variations. */
    class: Metriport.fhir.Coding;
    /** The class history permits the tracking of the encounters transitions without needing to go through the resource history. This would be used for a case where an admission starts of as an emergency encounter, then transitions into an inpatient scenario. Doing this and not restarting a new encounter ensures that any lab/diagnostic results can more easily follow the patient and not require re-processing and not get lost or cancelled during a kind of discharge from emergency to inpatient. */
    classHistory?: Metriport.fhir.EncounterClassHistory[];
    /** Specific type of encounter (e.g. e-mail consultation, surgical day-care, skilled nursing, rehabilitation). */
    type?: Metriport.fhir.CodeableConcept[];
    /** Broad categorization of the service that is to be provided (e.g. cardiology). */
    serviceType?: Metriport.fhir.CodeableConcept;
    /** Indicates the urgency of the encounter. */
    priority?: Metriport.fhir.CodeableConcept;
    /** The patient or group present at the encounter. */
    subject?: Metriport.fhir.Reference;
    /** Where a specific encounter should be classified as a part of a specific episode(s) of care this field should be used. This association can facilitate grouping of related encounters together for a specific purpose, such as government reporting, issue tracking, association via a common problem. The association is recorded on the encounter as these are typically created after the episode of care and grouped on entry rather than editing the episode of care to append another encounter to it (the episode of care could span years). */
    episodeOfCare?: Metriport.fhir.Reference[];
    /** The request this encounter satisfies (e.g. incoming referral or procedure request). */
    basedOn?: Metriport.fhir.Reference[];
    /** The list of people responsible for providing the service. */
    participant?: Metriport.fhir.EncounterParticipant[];
    /** The appointment that scheduled this encounter. */
    appointment?: Metriport.fhir.Reference[];
    /** The start and end time of the encounter. */
    period?: Metriport.fhir.Period;
    /** Quantity of time the encounter lasted. This excludes the time during leaves of absence. */
    length?: Metriport.fhir.Duration;
    /** Reason the encounter takes place, expressed as a code. For admissions, this can be used for a coded admission diagnosis. */
    reasonCode?: Metriport.fhir.CodeableConcept[];
    /** Reason the encounter takes place, expressed as a code. For admissions, this can be used for a coded admission diagnosis. */
    reasonReference?: Metriport.fhir.Reference[];
    /** The list of diagnosis relevant to this encounter. */
    diagnosis?: Metriport.fhir.EncounterDiagnosis[];
    /** The set of accounts that may be used for billing for this Encounter. */
    account?: Metriport.fhir.Reference[];
    /** Details about the admission to a healthcare service. */
    hospitalization?: Metriport.fhir.EncounterHospitalization;
    /** List of locations where the patient has been during this encounter. */
    location?: Metriport.fhir.EncounterLocation[];
    /** The organization that is primarily responsible for this Encounter's services. This MAY be the same as the organization on the Patient record, however it could be different, such as if the actor performing the services was from an external organization (which may be billed seperately) for an external consultation. Refer to the example bundle showing an abbreviated set of Encounters for a colonoscopy. */
    serviceProvider?: Metriport.fhir.Reference;
    /** Another Encounter of which this encounter is a part of (administratively or in time). */
    partOf?: Metriport.fhir.Reference;
}
