/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the participants' presence at the specified location during the period specified. If the participant is no longer at the location, then the period will have an end date/time.
 */
export type EncounterLocationStatus = "planned" | "active" | "reserved" | "completed";

export const EncounterLocationStatus = {
    Planned: "planned",
    Active: "active",
    Reserved: "reserved",
    Completed: "completed",
} as const;
