/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * This resource provides the insurance enrollment details to the insurer regarding a specified coverage.
 */
export interface EnrollmentRequest extends Metriport.fhir.BaseResource {
    resourceType: "EnrollmentRequest";
    /** The Response business identifier. */
    identifier?: Metriport.fhir.Identifier[];
    /** The status of the resource instance. */
    status?: Metriport.fhir.Code;
    /** The date when this resource was created. */
    created?: Metriport.fhir.DateTime;
    /** The Insurer who is target of the request. */
    insurer?: Metriport.fhir.Reference;
    /** The practitioner who is responsible for the services rendered to the patient. */
    provider?: Metriport.fhir.Reference;
    /** Patient Resource. */
    candidate?: Metriport.fhir.Reference;
    /** Reference to the program or plan identification, underwriter or payor. */
    coverage?: Metriport.fhir.Reference;
}
