/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * planned | waitlist | active | onhold | finished | cancelled.
 */
export type EpisodeOfCareStatus =
    | "planned"
    | "waitlist"
    | "active"
    | "onhold"
    | "finished"
    | "cancelled"
    | "entered-in-error";

export const EpisodeOfCareStatus = {
    Planned: "planned",
    Waitlist: "waitlist",
    Active: "active",
    Onhold: "onhold",
    Finished: "finished",
    Cancelled: "cancelled",
    EnteredInError: "entered-in-error",
} as const;
