/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of evidence element, a population, an exposure, or an outcome.
 */
export type EvidenceVariableType = "dichotomous" | "continuous" | "descriptive";

export const EvidenceVariableType = {
    Dichotomous: "dichotomous",
    Continuous: "continuous",
    Descriptive: "descriptive",
} as const;
