/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of actor - person or system.
 */
export type ExampleScenarioActorType = "person" | "entity";

export const ExampleScenarioActorType = {
    Person: "person",
    Entity: "entity",
} as const;
