/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Example of workflow instance.
 */
export interface ExampleScenario extends Metriport.fhir.BaseResource {
    resourceType: "ExampleScenario";
    /** An absolute URI that is used to identify this example scenario when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which at which an authoritative instance of this example scenario is (or will be) published. This URL can be the target of a canonical reference. It SHALL remain the same when the example scenario is stored on different servers. */
    url?: Metriport.fhir.Uri;
    /** A formal identifier that is used to identify this example scenario when it is represented in other formats, or referenced in a specification, model, design or an instance. */
    identifier?: Metriport.fhir.Identifier[];
    /** The identifier that is used to identify this version of the example scenario when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the example scenario author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence. */
    version?: string;
    /** A natural language name identifying the example scenario. This name should be usable as an identifier for the module by machine processing applications such as code generation. */
    name?: string;
    /** The status of this example scenario. Enables tracking the life-cycle of the content. */
    status?: Metriport.fhir.ExampleScenarioStatus;
    /** A Boolean value to indicate that this example scenario is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage. */
    experimental?: boolean;
    /** The date (and optionally time) when the example scenario was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the example scenario changes. (e.g. the 'content logical definition'). */
    date?: Metriport.fhir.DateTime;
    /** The name of the organization or individual that published the example scenario. */
    publisher?: string;
    /** Contact details to assist a user in finding and communicating with the publisher. */
    contact?: Metriport.fhir.ContactDetail[];
    /** The content was developed with a focus and intent of supporting the contexts that are listed. These contexts may be general categories (gender, age, ...) or may be references to specific programs (insurance plans, studies, ...) and may be used to assist with indexing and searching for appropriate example scenario instances. */
    useContext?: Metriport.fhir.UsageContext[];
    /** A legal or geographic region in which the example scenario is intended to be used. */
    jurisdiction?: Metriport.fhir.CodeableConcept[];
    /** A copyright statement relating to the example scenario and/or its contents. Copyright statements are generally legal restrictions on the use and publishing of the example scenario. */
    copyright?: Metriport.fhir.Markdown;
    /** What the example scenario resource is created for. This should not be used to show the business purpose of the scenario itself, but the purpose of documenting a scenario. */
    purpose?: Metriport.fhir.Markdown;
    /** Actor participating in the resource. */
    actor?: Metriport.fhir.ExampleScenarioActor[];
    /** Each resource and each version that is present in the workflow. */
    instance?: Metriport.fhir.ExampleScenarioInstance[];
    /** Each major process - a group of operations. */
    process?: Metriport.fhir.ExampleScenarioProcess[];
    /** Another nested workflow. */
    workflow?: Metriport.fhir.Canonical[];
}
