/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A code specifying the status of the record of the family history of a specific family member.
 */
export type FamilyMemberHistoryStatus = "partial" | "completed" | "entered-in-error" | "health-unknown";

export const FamilyMemberHistoryStatus = {
    Partial: "partial",
    Completed: "completed",
    EnteredInError: "entered-in-error",
    HealthUnknown: "health-unknown",
} as const;
