/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Defines how the compartment rule is used - whether it it is used to test whether resources are subject to the rule, or whether it is a rule that must be followed.
 */
export type GraphDefinitionCompartmentUse = "condition" | "requirement";

export const GraphDefinitionCompartmentUse = {
    Condition: "condition",
    Requirement: "requirement",
} as const;
