/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Identifies the broad classification of the kind of resources the group includes.
 */
export type GroupType = "person" | "animal" | "practitioner" | "device" | "medication" | "substance";

export const GroupType = {
    Person: "person",
    Animal: "animal",
    Practitioner: "practitioner",
    Device: "device",
    Medication: "medication",
    Substance: "substance",
} as const;
