/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type HealthcareServiceAvailableTimeDaysOfWeekItem = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";

export const HealthcareServiceAvailableTimeDaysOfWeekItem = {
    Mon: "mon",
    Tue: "tue",
    Wed: "wed",
    Thu: "thu",
    Fri: "fri",
    Sat: "sat",
    Sun: "sun",
} as const;
