/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Representation of the content produced in a DICOM imaging study. A study comprises a set of series, each of which includes a set of Service-Object Pair Instances (SOP Instances - images or other data) acquired or produced in a common context. A series is of only one modality (e.g. X-ray, CT, MR, ultrasound), but a study may have multiple series of different modalities.
 */
export interface ImagingStudy extends Metriport.fhir.BaseResource {
    resourceType: "ImagingStudy";
    /** Identifiers for the ImagingStudy such as DICOM Study Instance UID, and Accession Number. */
    identifier?: Metriport.fhir.Identifier[];
    /** The current state of the ImagingStudy. */
    status?: Metriport.fhir.ImagingStudyStatus;
    /** A list of all the series.modality values that are actual acquisition modalities, i.e. those in the DICOM Context Group 29 (value set OID 1.2.840.10008.6.1.19). */
    modality?: Metriport.fhir.Coding[];
    /** The subject, typically a patient, of the imaging study. */
    subject: Metriport.fhir.Reference;
    /** The healthcare event (e.g. a patient and healthcare provider interaction) during which this ImagingStudy is made. */
    encounter?: Metriport.fhir.Reference;
    /** Date and time the study started. */
    started?: Metriport.fhir.DateTime;
    /** A list of the diagnostic requests that resulted in this imaging study being performed. */
    basedOn?: Metriport.fhir.Reference[];
    /** The requesting/referring physician. */
    referrer?: Metriport.fhir.Reference;
    /** Who read the study and interpreted the images or other content. */
    interpreter?: Metriport.fhir.Reference[];
    /** The network service providing access (e.g., query, view, or retrieval) for the study. See implementation notes for information about using DICOM endpoints. A study-level endpoint applies to each series in the study, unless overridden by a series-level endpoint with the same Endpoint.connectionType. */
    endpoint?: Metriport.fhir.Reference[];
    /** Number of Series in the Study. This value given may be larger than the number of series elements this Resource contains due to resource availability, security, or other factors. This element should be present if any series elements are present. */
    numberOfSeries?: Metriport.fhir.UnsignedInt;
    /** Number of SOP Instances in Study. This value given may be larger than the number of instance elements this resource contains due to resource availability, security, or other factors. This element should be present if any instance elements are present. */
    numberOfInstances?: Metriport.fhir.UnsignedInt;
    /** The procedure which this ImagingStudy was part of. */
    procedureReference?: Metriport.fhir.Reference;
    /** The code for the performed procedure type. */
    procedureCode?: Metriport.fhir.CodeableConcept[];
    /** The principal physical location where the ImagingStudy was performed. */
    location?: Metriport.fhir.Reference;
    /** Description of clinical condition indicating why the ImagingStudy was requested. */
    reasonCode?: Metriport.fhir.CodeableConcept[];
    /** Indicates another resource whose existence justifies this Study. */
    reasonReference?: Metriport.fhir.Reference[];
    /** Per the recommended DICOM mapping, this element is derived from the Study Description attribute (0008,1030). Observations or findings about the imaging study should be recorded in another resource, e.g. Observation, and not in this element. */
    note?: Metriport.fhir.Annotation[];
    /** The Imaging Manager description of the study. Institution-generated description or classification of the Study (component) performed. */
    description?: string;
    /** Each study has one or more series of images or other content. */
    series?: Metriport.fhir.ImagingStudySeries[];
}
