/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * apply | path-resource | path-pages | path-tx-cache | expansion-parameter | rule-broken-links | generate-xml | generate-json | generate-turtle | html-template.
 */
export type ImplementationGuideParameterCode =
    | "apply"
    | "path-resource"
    | "path-pages"
    | "path-tx-cache"
    | "expansion-parameter"
    | "rule-broken-links"
    | "generate-xml"
    | "generate-json"
    | "generate-turtle"
    | "html-template";

export const ImplementationGuideParameterCode = {
    Apply: "apply",
    PathResource: "path-resource",
    PathPages: "path-pages",
    PathTxCache: "path-tx-cache",
    ExpansionParameter: "expansion-parameter",
    RuleBrokenLinks: "rule-broken-links",
    GenerateXml: "generate-xml",
    GenerateJson: "generate-json",
    GenerateTurtle: "generate-turtle",
    HtmlTemplate: "html-template",
} as const;
