/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A code that indicates how the page is generated.
 */
export type ImplementationGuidePageGeneration = "html" | "markdown" | "xml" | "generated";

export const ImplementationGuidePageGeneration = {
    Html: "html",
    Markdown: "markdown",
    Xml: "xml",
    Generated: "generated",
} as const;
