/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ImplementationGuideResourceFhirVersionItem =
    | "0.01"
    | "0.05"
    | "0.06"
    | "0.11"
    | "0.0.80"
    | "0.0.81"
    | "0.0.82"
    | "0.4.0"
    | "0.5.0"
    | "1.0.0"
    | "1.0.1"
    | "1.0.2"
    | "1.1.0"
    | "1.4.0"
    | "1.6.0"
    | "1.8.0"
    | "3.0.0"
    | "3.0.1"
    | "3.3.0"
    | "3.5.0"
    | "4.0.0"
    | "4.0.1";

export const ImplementationGuideResourceFhirVersionItem = {
    Zero01: "0.01",
    Zero05: "0.05",
    Zero06: "0.06",
    Zero11: "0.11",
    Zero080: "0.0.80",
    Zero081: "0.0.81",
    Zero082: "0.0.82",
    Zero40: "0.4.0",
    Zero50: "0.5.0",
    One00: "1.0.0",
    One01: "1.0.1",
    One02: "1.0.2",
    One10: "1.1.0",
    One40: "1.4.0",
    One60: "1.6.0",
    One80: "1.8.0",
    Three00: "3.0.0",
    Three01: "3.0.1",
    Three30: "3.3.0",
    Three50: "3.5.0",
    Four00: "4.0.0",
    Four01: "4.0.1",
} as const;
