/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Details of a Health Insurance product/plan provided by an organization.
 */
export interface InsurancePlan extends Metriport.fhir.BaseResource {
    resourceType: "InsurancePlan";
    /** Business identifiers assigned to this health insurance product which remain constant as the resource is updated and propagates from server to server. */
    identifier?: Metriport.fhir.Identifier[];
    /** The current state of the health insurance product. */
    status?: Metriport.fhir.InsurancePlanStatus;
    /** The kind of health insurance product. */
    type?: Metriport.fhir.CodeableConcept[];
    /** Official name of the health insurance product as designated by the owner. */
    name?: string;
    /** A list of alternate names that the product is known as, or was known as in the past. */
    alias?: string[];
    /** The period of time that the health insurance product is available. */
    period?: Metriport.fhir.Period;
    /** The entity that is providing the health insurance product and underwriting the risk. This is typically an insurance carriers, other third-party payers, or health plan sponsors comonly referred to as 'payers'. */
    ownedBy?: Metriport.fhir.Reference;
    /** An organization which administer other services such as underwriting, customer service and/or claims processing on behalf of the health insurance product owner. */
    administeredBy?: Metriport.fhir.Reference;
    /** The geographic region in which a health insurance product's benefits apply. */
    coverageArea?: Metriport.fhir.Reference[];
    /** The contact for the health insurance product for a certain purpose. */
    contact?: Metriport.fhir.InsurancePlanContact[];
    /** The technical endpoints providing access to services operated for the health insurance product. */
    endpoint?: Metriport.fhir.Reference[];
    /** Reference to the network included in the health insurance product. */
    network?: Metriport.fhir.Reference[];
    /** Details about the coverage offered by the insurance product. */
    coverage?: Metriport.fhir.InsurancePlanCoverage[];
    /** Details about an insurance plan. */
    plan?: Metriport.fhir.InsurancePlanPlan[];
}
