/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current state of the Invoice.
 */
export type InvoiceStatus = "draft" | "issued" | "balanced" | "cancelled" | "entered-in-error";

export const InvoiceStatus = {
    Draft: "draft",
    Issued: "issued",
    Balanced: "balanced",
    Cancelled: "cancelled",
    EnteredInError: "entered-in-error",
} as const;
