/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * The Library resource is a general-purpose container for knowledge asset definitions. It can be used to describe and expose existing knowledge assets such as logic libraries and information model descriptions, as well as to describe a collection of knowledge assets.
 */
export interface Library extends Metriport.fhir.BaseResource {
    resourceType: "Library";
    /** An absolute URI that is used to identify this library when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which at which an authoritative instance of this library is (or will be) published. This URL can be the target of a canonical reference. It SHALL remain the same when the library is stored on different servers. */
    url?: Metriport.fhir.Uri;
    /** A formal identifier that is used to identify this library when it is represented in other formats, or referenced in a specification, model, design or an instance. e.g. CMS or NQF identifiers for a measure artifact. Note that at least one identifier is required for non-experimental active artifacts. */
    identifier?: Metriport.fhir.Identifier[];
    /** The identifier that is used to identify this version of the library when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the library author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence. To provide a version consistent with the Decision Support Service specification, use the format Major.Minor.Revision (e.g. 1.0.0). For more information on versioning knowledge assets, refer to the Decision Support Service specification. Note that a version is required for non-experimental active artifacts. */
    version?: string;
    /** A natural language name identifying the library. This name should be usable as an identifier for the module by machine processing applications such as code generation. */
    name?: string;
    /** A short, descriptive, user-friendly title for the library. */
    title?: string;
    /** An explanatory or alternate title for the library giving additional information about its content. */
    subtitle?: string;
    /** The status of this library. Enables tracking the life-cycle of the content. */
    status?: Metriport.fhir.LibraryStatus;
    /** A Boolean value to indicate that this library is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage. */
    experimental?: boolean;
    /** Identifies the type of library such as a Logic Library, Model Definition, Asset Collection, or Module Definition. */
    type: Metriport.fhir.CodeableConcept;
    /** A code or group definition that describes the intended subject of the contents of the library. */
    subjectCodeableConcept?: Metriport.fhir.CodeableConcept;
    /** A code or group definition that describes the intended subject of the contents of the library. */
    subjectReference?: Metriport.fhir.Reference;
    /** The date (and optionally time) when the library was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the library changes. */
    date?: Metriport.fhir.DateTime;
    /** The name of the organization or individual that published the library. */
    publisher?: string;
    /** Contact details to assist a user in finding and communicating with the publisher. */
    contact?: Metriport.fhir.ContactDetail[];
    /** A free text natural language description of the library from a consumer's perspective. */
    description?: Metriport.fhir.Markdown;
    /** The content was developed with a focus and intent of supporting the contexts that are listed. These contexts may be general categories (gender, age, ...) or may be references to specific programs (insurance plans, studies, ...) and may be used to assist with indexing and searching for appropriate library instances. */
    useContext?: Metriport.fhir.UsageContext[];
    /** A legal or geographic region in which the library is intended to be used. */
    jurisdiction?: Metriport.fhir.CodeableConcept[];
    /** Explanation of why this library is needed and why it has been designed as it has. */
    purpose?: Metriport.fhir.Markdown;
    /** A detailed description of how the library is used from a clinical perspective. */
    usage?: string;
    /** A copyright statement relating to the library and/or its contents. Copyright statements are generally legal restrictions on the use and publishing of the library. */
    copyright?: Metriport.fhir.Markdown;
    /** The date on which the resource content was approved by the publisher. Approval happens once when the content is officially approved for usage. */
    approvalDate?: string;
    /** The date on which the resource content was last reviewed. Review happens periodically after approval but does not change the original approval date. */
    lastReviewDate?: string;
    /** The period during which the library content was or is planned to be in active use. */
    effectivePeriod?: Metriport.fhir.Period;
    /** Descriptive topics related to the content of the library. Topics provide a high-level categorization of the library that can be useful for filtering and searching. */
    topic?: Metriport.fhir.CodeableConcept[];
    /** An individiual or organization primarily involved in the creation and maintenance of the content. */
    author?: Metriport.fhir.ContactDetail[];
    /** An individual or organization primarily responsible for internal coherence of the content. */
    editor?: Metriport.fhir.ContactDetail[];
    /** An individual or organization primarily responsible for review of some aspect of the content. */
    reviewer?: Metriport.fhir.ContactDetail[];
    /** An individual or organization responsible for officially endorsing the content for use in some setting. */
    endorser?: Metriport.fhir.ContactDetail[];
    /** Related artifacts such as additional documentation, justification, or bibliographic references. */
    relatedArtifact?: Metriport.fhir.RelatedArtifact[];
    /** The parameter element defines parameters used by the library. */
    parameter?: Metriport.fhir.ParameterDefinition[];
    /** Describes a set of data that must be provided in order to be able to successfully perform the computations defined by the library. */
    dataRequirement?: Metriport.fhir.DataRequirement[];
    /** The content of the library as an Attachment. The content may be a reference to a url, or may be directly embedded as a base-64 string. Either way, the contentType of the attachment determines how to interpret the content. */
    content?: Metriport.fhir.Attachment[];
}
