/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Identifies two or more records (resource instances) that refer to the same real-world "occurrence".
 */
export interface Linkage extends Metriport.fhir.BaseResource {
    resourceType: "Linkage";
    /** Indicates whether the asserted set of linkages are considered to be "in effect". */
    active?: boolean;
    /** Identifies the user or organization responsible for asserting the linkages as well as the user or organization who establishes the context in which the nature of each linkage is evaluated. */
    author?: Metriport.fhir.Reference;
    /** Identifies which record considered as the reference to the same real-world occurrence as well as how the items should be evaluated within the collection of linked items. */
    item: Metriport.fhir.LinkageItem[];
}
