/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates the current state of this list.
 */
export type ListStatus = "current" | "retired" | "entered-in-error";

export const ListStatus = {
    Current: "current",
    Retired: "retired",
    EnteredInError: "entered-in-error",
} as const;
