/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates whether a resource instance represents a specific location or a class of locations.
 */
export type LocationMode = "instance" | "kind";

export const LocationMode = {
    Instance: "instance",
    Kind: "kind",
} as const;
