/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * The Measure resource provides the definition of a quality measure.
 */
export interface Measure extends Metriport.fhir.BaseResource {
    resourceType: "Measure";
    /** An absolute URI that is used to identify this measure when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which at which an authoritative instance of this measure is (or will be) published. This URL can be the target of a canonical reference. It SHALL remain the same when the measure is stored on different servers. */
    url?: Metriport.fhir.Uri;
    /** A formal identifier that is used to identify this measure when it is represented in other formats, or referenced in a specification, model, design or an instance. */
    identifier?: Metriport.fhir.Identifier[];
    /** The identifier that is used to identify this version of the measure when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the measure author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence. To provide a version consistent with the Decision Support Service specification, use the format Major.Minor.Revision (e.g. 1.0.0). For more information on versioning knowledge assets, refer to the Decision Support Service specification. Note that a version is required for non-experimental active artifacts. */
    version?: string;
    /** A natural language name identifying the measure. This name should be usable as an identifier for the module by machine processing applications such as code generation. */
    name?: string;
    /** A short, descriptive, user-friendly title for the measure. */
    title?: string;
    /** An explanatory or alternate title for the measure giving additional information about its content. */
    subtitle?: string;
    /** The status of this measure. Enables tracking the life-cycle of the content. */
    status?: Metriport.fhir.MeasureStatus;
    /** A Boolean value to indicate that this measure is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage. */
    experimental?: boolean;
    /** The intended subjects for the measure. If this element is not provided, a Patient subject is assumed, but the subject of the measure can be anything. */
    subjectCodeableConcept?: Metriport.fhir.CodeableConcept;
    /** The intended subjects for the measure. If this element is not provided, a Patient subject is assumed, but the subject of the measure can be anything. */
    subjectReference?: Metriport.fhir.Reference;
    /** The date (and optionally time) when the measure was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the measure changes. */
    date?: Metriport.fhir.DateTime;
    /** The name of the organization or individual that published the measure. */
    publisher?: string;
    /** Contact details to assist a user in finding and communicating with the publisher. */
    contact?: Metriport.fhir.ContactDetail[];
    /** A free text natural language description of the measure from a consumer's perspective. */
    description?: Metriport.fhir.Markdown;
    /** The content was developed with a focus and intent of supporting the contexts that are listed. These contexts may be general categories (gender, age, ...) or may be references to specific programs (insurance plans, studies, ...) and may be used to assist with indexing and searching for appropriate measure instances. */
    useContext?: Metriport.fhir.UsageContext[];
    /** A legal or geographic region in which the measure is intended to be used. */
    jurisdiction?: Metriport.fhir.CodeableConcept[];
    /** Explanation of why this measure is needed and why it has been designed as it has. */
    purpose?: Metriport.fhir.Markdown;
    /** A detailed description, from a clinical perspective, of how the measure is used. */
    usage?: string;
    /** A copyright statement relating to the measure and/or its contents. Copyright statements are generally legal restrictions on the use and publishing of the measure. */
    copyright?: Metriport.fhir.Markdown;
    /** The date on which the resource content was approved by the publisher. Approval happens once when the content is officially approved for usage. */
    approvalDate?: string;
    /** The date on which the resource content was last reviewed. Review happens periodically after approval but does not change the original approval date. */
    lastReviewDate?: string;
    /** The period during which the measure content was or is planned to be in active use. */
    effectivePeriod?: Metriport.fhir.Period;
    /** Descriptive topics related to the content of the measure. Topics provide a high-level categorization grouping types of measures that can be useful for filtering and searching. */
    topic?: Metriport.fhir.CodeableConcept[];
    /** An individiual or organization primarily involved in the creation and maintenance of the content. */
    author?: Metriport.fhir.ContactDetail[];
    /** An individual or organization primarily responsible for internal coherence of the content. */
    editor?: Metriport.fhir.ContactDetail[];
    /** An individual or organization primarily responsible for review of some aspect of the content. */
    reviewer?: Metriport.fhir.ContactDetail[];
    /** An individual or organization responsible for officially endorsing the content for use in some setting. */
    endorser?: Metriport.fhir.ContactDetail[];
    /** Related artifacts such as additional documentation, justification, or bibliographic references. */
    relatedArtifact?: Metriport.fhir.RelatedArtifact[];
    /** A reference to a Library resource containing the formal logic used by the measure. */
    library?: Metriport.fhir.Canonical[];
    /** Notices and disclaimers regarding the use of the measure or related to intellectual property (such as code systems) referenced by the measure. */
    disclaimer?: Metriport.fhir.Markdown;
    /** Indicates how the calculation is performed for the measure, including proportion, ratio, continuous-variable, and cohort. The value set is extensible, allowing additional measure scoring types to be represented. */
    scoring?: Metriport.fhir.CodeableConcept;
    /** If this is a composite measure, the scoring method used to combine the component measures to determine the composite score. */
    compositeScoring?: Metriport.fhir.CodeableConcept;
    /** Indicates whether the measure is used to examine a process, an outcome over time, a patient-reported outcome, or a structure measure such as utilization. */
    type?: Metriport.fhir.CodeableConcept[];
    /** A description of the risk adjustment factors that may impact the resulting score for the measure and how they may be accounted for when computing and reporting measure results. */
    riskAdjustment?: string;
    /** Describes how to combine the information calculated, based on logic in each of several populations, into one summarized result. */
    rateAggregation?: string;
    /** Provides a succinct statement of the need for the measure. Usually includes statements pertaining to importance criterion: impact, gap in care, and evidence. */
    rationale?: Metriport.fhir.Markdown;
    /** Provides a summary of relevant clinical guidelines or other clinical recommendations supporting the measure. */
    clinicalRecommendationStatement?: Metriport.fhir.Markdown;
    /** Information on whether an increase or decrease in score is the preferred result (e.g., a higher score indicates better quality OR a lower score indicates better quality OR quality is within a range). */
    improvementNotation?: Metriport.fhir.CodeableConcept;
    /** Provides a description of an individual term used within the measure. */
    definition?: Metriport.fhir.Markdown[];
    /** Additional guidance for the measure including how it can be used in a clinical context, and the intent of the measure. */
    guidance?: Metriport.fhir.Markdown;
    /** A group of population criteria for the measure. */
    group?: Metriport.fhir.MeasureGroup[];
    /** The supplemental data criteria for the measure report, specified as either the name of a valid CQL expression within a referenced library, or a valid FHIR Resource Path. */
    supplementalData?: Metriport.fhir.MeasureSupplementalData[];
}
