/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A pharmaceutical product described in terms of its composition and dose form.
 */
export interface MedicinalProductPharmaceutical extends Metriport.fhir.BaseResource {
    resourceType: "MedicinalProductPharmaceutical";
    /** An identifier for the pharmaceutical medicinal product. */
    identifier?: Metriport.fhir.Identifier[];
    /** The administrable dose form, after necessary reconstitution. */
    administrableDoseForm: Metriport.fhir.CodeableConcept;
    /** Todo. */
    unitOfPresentation?: Metriport.fhir.CodeableConcept;
    /** Ingredient. */
    ingredient?: Metriport.fhir.Reference[];
    /** Accompanying device. */
    device?: Metriport.fhir.Reference[];
    /** Characteristics e.g. a products onset of action. */
    characteristics?: Metriport.fhir.MedicinalProductPharmaceuticalCharacteristics[];
    /** The path by which the pharmaceutical product is taken into or makes contact with the body. */
    routeOfAdministration: Metriport.fhir.MedicinalProductPharmaceuticalRouteOfAdministration[];
}
