/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Indicates that a medication product is to be or has been dispensed for a named person/patient. This includes a description of the medication product (supply) provided and the instructions for administering the medication. The medication dispense is the result of a pharmacy system responding to a medication order.
 */
export interface MedicationDispense extends Metriport.fhir.BaseResource {
    resourceType: "MedicationDispense";
    /** Identifiers associated with this Medication Dispense that are defined by business processes and/or used to refer to it when a direct URL reference to the resource itself is not appropriate. They are business identifiers assigned to this resource by the performer or other systems and remain constant as the resource is updated and propagates from server to server. */
    identifier?: Metriport.fhir.Identifier[];
    /** The procedure that trigger the dispense. */
    partOf?: Metriport.fhir.Reference[];
    /** A code specifying the state of the set of dispense events. */
    status?: Metriport.fhir.Code;
    /** Indicates the reason why a dispense was not performed. */
    statusReasonCodeableConcept?: Metriport.fhir.CodeableConcept;
    /** Indicates the reason why a dispense was not performed. */
    statusReasonReference?: Metriport.fhir.Reference;
    /** Indicates the type of medication dispense (for example, where the medication is expected to be consumed or administered (i.e. inpatient or outpatient)). */
    category?: Metriport.fhir.CodeableConcept;
    /** Identifies the medication being administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication from a known list of medications. */
    medicationCodeableConcept?: Metriport.fhir.CodeableConcept;
    /** Identifies the medication being administered. This is either a link to a resource representing the details of the medication or a simple attribute carrying a code that identifies the medication from a known list of medications. */
    medicationReference?: Metriport.fhir.Reference;
    /** A link to a resource representing the person or the group to whom the medication will be given. */
    subject?: Metriport.fhir.Reference;
    /** The encounter or episode of care that establishes the context for this event. */
    context?: Metriport.fhir.Reference;
    /** Additional information that supports the medication being dispensed. */
    supportingInformation?: Metriport.fhir.Reference[];
    /** Indicates who or what performed the event. */
    performer?: Metriport.fhir.MedicationDispensePerformer[];
    /** The principal physical location where the dispense was performed. */
    location?: Metriport.fhir.Reference;
    /** Indicates the medication order that is being dispensed against. */
    authorizingPrescription?: Metriport.fhir.Reference[];
    /** Indicates the type of dispensing event that is performed. For example, Trial Fill, Completion of Trial, Partial Fill, Emergency Fill, Samples, etc. */
    type?: Metriport.fhir.CodeableConcept;
    /** The amount of medication that has been dispensed. Includes unit of measure. */
    quantity?: Metriport.fhir.Quantity;
    /** The amount of medication expressed as a timing amount. */
    daysSupply?: Metriport.fhir.Quantity;
    /** The time when the dispensed product was packaged and reviewed. */
    whenPrepared?: Metriport.fhir.DateTime;
    /** The time the dispensed product was provided to the patient or their representative. */
    whenHandedOver?: Metriport.fhir.DateTime;
    /** Identification of the facility/location where the medication was shipped to, as part of the dispense event. */
    destination?: Metriport.fhir.Reference;
    /** Identifies the person who picked up the medication. This will usually be a patient or their caregiver, but some cases exist where it can be a healthcare professional. */
    receiver?: Metriport.fhir.Reference[];
    /** Extra information about the dispense that could not be conveyed in the other attributes. */
    note?: Metriport.fhir.Annotation[];
    /** Indicates how the medication is to be used by the patient. */
    dosageInstruction?: Metriport.fhir.Dosage[];
    /** Indicates whether or not substitution was made as part of the dispense. In some cases, substitution will be expected but does not happen, in other cases substitution is not expected but does happen. This block explains what substitution did or did not happen and why. If nothing is specified, substitution was not done. */
    substitution?: Metriport.fhir.MedicationDispenseSubstitution;
    /** Indicates an actual or potential clinical issue with or between one or more active or proposed clinical actions for a patient; e.g. drug-drug interaction, duplicate therapy, dosage alert etc. */
    detectedIssue?: Metriport.fhir.Reference[];
    /** A summary of the events of interest that have occurred, such as when the dispense was verified. */
    eventHistory?: Metriport.fhir.Reference[];
}
