/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Amino Acid Sequence/ DNA Sequence / RNA Sequence.
 */
export type MolecularSequenceType = "aa" | "dna" | "rna";

export const MolecularSequenceType = {
    Aa: "aa",
    Dna: "dna",
    Rna: "rna",
} as const;
