/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Raw data describing a biological sequence.
 */
export interface MolecularSequenceQuality {
    /** Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces. */
    id?: string;
    /** May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. */
    extension?: Metriport.fhir.Extension[];
    /** May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions. Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself). */
    modifierExtension?: Metriport.fhir.Extension[];
    /** INDEL / SNP / Undefined variant. */
    type?: Metriport.fhir.MolecularSequenceQualityType;
    /** Gold standard sequence used for comparing against. */
    standardSequence?: Metriport.fhir.CodeableConcept;
    /** Start position of the sequence. If the coordinate system is either 0-based or 1-based, then start position is inclusive. */
    start?: number;
    /** End position of the sequence. If the coordinate system is 0-based then end is exclusive and does not include the last position. If the coordinate system is 1-base, then end is inclusive and includes the last position. */
    end?: number;
    /** The score of an experimentally derived feature such as a p-value ([SO:0001685](http://www.sequenceontology.org/browser/current_svn/term/SO:0001685)). */
    score?: Metriport.fhir.Quantity;
    /** Which method is used to get sequence quality. */
    method?: Metriport.fhir.CodeableConcept;
    /** True positives, from the perspective of the truth data, i.e. the number of sites in the Truth Call Set for which there are paths through the Query Call Set that are consistent with all of the alleles at this site, and for which there is an accurate genotype call for the event. */
    truthTP?: Metriport.fhir.Decimal;
    /** True positives, from the perspective of the query data, i.e. the number of sites in the Query Call Set for which there are paths through the Truth Call Set that are consistent with all of the alleles at this site, and for which there is an accurate genotype call for the event. */
    queryTP?: Metriport.fhir.Decimal;
    /** False negatives, i.e. the number of sites in the Truth Call Set for which there is no path through the Query Call Set that is consistent with all of the alleles at this site, or sites for which there is an inaccurate genotype call for the event. Sites with correct variant but incorrect genotype are counted here. */
    truthFN?: Metriport.fhir.Decimal;
    /** False positives, i.e. the number of sites in the Query Call Set for which there is no path through the Truth Call Set that is consistent with this site. Sites with correct variant but incorrect genotype are counted here. */
    queryFP?: Metriport.fhir.Decimal;
    /** The number of false positives where the non-REF alleles in the Truth and Query Call Sets match (i.e. cases where the truth is 1/1 and the query is 0/1 or similar). */
    gtFP?: Metriport.fhir.Decimal;
    /** QUERY.TP / (QUERY.TP + QUERY.FP). */
    precision?: Metriport.fhir.Decimal;
    /** TRUTH.TP / (TRUTH.TP + TRUTH.FN). */
    recall?: Metriport.fhir.Decimal;
    /** Harmonic mean of Recall and Precision, computed as: 2 _ precision _ recall / (precision + recall). */
    fScore?: Metriport.fhir.Decimal;
    /** Receiver Operator Characteristic (ROC) Curve to give sensitivity/specificity tradeoff. */
    roc?: Metriport.fhir.MolecularSequenceRoc;
}
