/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * An absolute reference to a strand. The Watson strand is the strand whose 5'-end is on the short arm of the chromosome, and the Crick strand as the one whose 5'-end is on the long arm.
 */
export type MolecularSequenceReferenceSeqStrand = "watson" | "crick";

export const MolecularSequenceReferenceSeqStrand = {
    Watson: "watson",
    Crick: "crick",
} as const;
