/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Identifies the unique identifier scheme used for this particular identifier.
 */
export type NamingSystemUniqueIdType = "oid" | "uuid" | "uri" | "other";

export const NamingSystemUniqueIdType = {
    Oid: "oid",
    Uuid: "uuid",
    Uri: "uri",
    Other: "other",
} as const;
