/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A curated namespace that issues unique symbols within that namespace for the identification of concepts, people, devices, etc. Represents a "System" used within the Identifier and Coding data types.
 */
export interface NamingSystem extends Metriport.fhir.BaseResource {
    resourceType: "NamingSystem";
    /** A natural language name identifying the naming system. This name should be usable as an identifier for the module by machine processing applications such as code generation. */
    name?: string;
    /** The status of this naming system. Enables tracking the life-cycle of the content. */
    status?: Metriport.fhir.NamingSystemStatus;
    /** Indicates the purpose for the naming system - what kinds of things does it make unique? */
    kind?: Metriport.fhir.NamingSystemKind;
    /** The date (and optionally time) when the naming system was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the naming system changes. */
    date?: Metriport.fhir.DateTime;
    /** The name of the organization or individual that published the naming system. */
    publisher?: string;
    /** Contact details to assist a user in finding and communicating with the publisher. */
    contact?: Metriport.fhir.ContactDetail[];
    /** The name of the organization that is responsible for issuing identifiers or codes for this namespace and ensuring their non-collision. */
    responsible?: string;
    /** Categorizes a naming system for easier search by grouping related naming systems. */
    type?: Metriport.fhir.CodeableConcept;
    /** A free text natural language description of the naming system from a consumer's perspective. Details about what the namespace identifies including scope, granularity, version labeling, etc. */
    description?: Metriport.fhir.Markdown;
    /** The content was developed with a focus and intent of supporting the contexts that are listed. These contexts may be general categories (gender, age, ...) or may be references to specific programs (insurance plans, studies, ...) and may be used to assist with indexing and searching for appropriate naming system instances. */
    useContext?: Metriport.fhir.UsageContext[];
    /** A legal or geographic region in which the naming system is intended to be used. */
    jurisdiction?: Metriport.fhir.CodeableConcept[];
    /** Provides guidance on the use of the namespace, including the handling of formatting characters, use of upper vs. lower case, etc. */
    usage?: string;
    /** Indicates how the system may be identified when referenced in electronic exchange. */
    uniqueId: Metriport.fhir.NamingSystemUniqueId[];
}
