/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the narrative - whether it's entirely generated (from just the defined data or the extensions too), or whether a human authored it and it may contain additional data.
 */
export type NarrativeStatus = "generated" | "extensions" | "additional" | "empty";

export const NarrativeStatus = {
    Generated: "generated",
    Extensions: "extensions",
    Additional: "additional",
    Empty: "empty",
} as const;
