/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A request to supply a diet, formula feeding (enteral) or oral nutritional supplement to a patient/resident.
 */
export interface NutritionOrder extends Metriport.fhir.BaseResource {
    resourceType: "NutritionOrder";
    /** Identifiers assigned to this order by the order sender or by the order receiver. */
    identifier?: Metriport.fhir.Identifier[];
    /** The URL pointing to a FHIR-defined protocol, guideline, orderset or other definition that is adhered to in whole or in part by this NutritionOrder. */
    instantiatesCanonical?: Metriport.fhir.Canonical[];
    /** The URL pointing to an externally maintained protocol, guideline, orderset or other definition that is adhered to in whole or in part by this NutritionOrder. */
    instantiatesUri?: Metriport.fhir.Uri[];
    /** The URL pointing to a protocol, guideline, orderset or other definition that is adhered to in whole or in part by this NutritionOrder. */
    instantiates?: Metriport.fhir.Uri[];
    /** The workflow status of the nutrition order/request. */
    status?: Metriport.fhir.Code;
    /** Indicates the level of authority/intentionality associated with the NutrionOrder and where the request fits into the workflow chain. */
    intent?: Metriport.fhir.Code;
    /** The person (patient) who needs the nutrition order for an oral diet, nutritional supplement and/or enteral or formula feeding. */
    patient: Metriport.fhir.Reference;
    /** An encounter that provides additional information about the healthcare context in which this request is made. */
    encounter?: Metriport.fhir.Reference;
    /** The date and time that this nutrition order was requested. */
    dateTime?: Metriport.fhir.DateTime;
    /** The practitioner that holds legal responsibility for ordering the diet, nutritional supplement, or formula feedings. */
    orderer?: Metriport.fhir.Reference;
    /** A link to a record of allergies or intolerances which should be included in the nutrition order. */
    allergyIntolerance?: Metriport.fhir.Reference[];
    /** This modifier is used to convey order-specific modifiers about the type of food that should be given. These can be derived from patient allergies, intolerances, or preferences such as Halal, Vegan or Kosher. This modifier applies to the entire nutrition order inclusive of the oral diet, nutritional supplements and enteral formula feedings. */
    foodPreferenceModifier?: Metriport.fhir.CodeableConcept[];
    /** This modifier is used to convey Order-specific modifier about the type of oral food or oral fluids that should not be given. These can be derived from patient allergies, intolerances, or preferences such as No Red Meat, No Soy or No Wheat or Gluten-Free. While it should not be necessary to repeat allergy or intolerance information captured in the referenced AllergyIntolerance resource in the excludeFoodModifier, this element may be used to convey additional specificity related to foods that should be eliminated from the patient’s diet for any reason. This modifier applies to the entire nutrition order inclusive of the oral diet, nutritional supplements and enteral formula feedings. */
    excludeFoodModifier?: Metriport.fhir.CodeableConcept[];
    /** Diet given orally in contrast to enteral (tube) feeding. */
    oralDiet?: Metriport.fhir.NutritionOrderOralDiet;
    /** Oral nutritional products given in order to add further nutritional value to the patient's diet. */
    supplement?: Metriport.fhir.NutritionOrderSupplement[];
    /** Feeding provided through the gastrointestinal tract via a tube, catheter, or stoma that delivers nutrition distal to the oral cavity. */
    enteralFormula?: Metriport.fhir.NutritionOrderEnteralFormula;
    /** Comments made about the {{title}} by the requester, performer, subject or other participants. */
    note?: Metriport.fhir.Annotation[];
}
