/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The category of interval of values for continuous or ordinal observations conforming to this ObservationDefinition.
 */
export type ObservationDefinitionQualifiedIntervalCategory = "reference" | "critical" | "absolute";

export const ObservationDefinitionQualifiedIntervalCategory = {
    Reference: "reference",
    Critical: "critical",
    Absolute: "absolute",
} as const;
