/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the result value.
 */
export type ObservationStatus =
    | "registered"
    | "preliminary"
    | "final"
    | "amended"
    | "corrected"
    | "cancelled"
    | "entered-in-error"
    | "unknown";

export const ObservationStatus = {
    Registered: "registered",
    Preliminary: "preliminary",
    Final: "final",
    Amended: "amended",
    Corrected: "corrected",
    Cancelled: "cancelled",
    EnteredInError: "entered-in-error",
    Unknown: "unknown",
} as const;
