/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A collection of error, warning, or information messages that result from a system action.
 */
export interface OperationOutcome extends Metriport.fhir.BaseResource {
    resourceType: "OperationOutcome";
    /** An error, warning, or information message that results from a system action. */
    issue: Metriport.fhir.OperationOutcomeIssue[];
    /** Optional HTTP status code returned by the operation. */
    status?: number;
    /** Optional Resource created or modified by this operation. */
    resource?: unknown;
}
