/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A formal computable definition of an operation (on the RESTful interface) or a named query (using the search interaction).
 */
export interface OperationDefinition extends Metriport.fhir.BaseResource {
    resourceType: "OperationDefinition";
    /** An absolute URI that is used to identify this operation definition when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which at which an authoritative instance of this operation definition is (or will be) published. This URL can be the target of a canonical reference. It SHALL remain the same when the operation definition is stored on different servers. */
    url?: Metriport.fhir.Uri;
    /** The identifier that is used to identify this version of the operation definition when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the operation definition author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence. */
    version?: string;
    /** A natural language name identifying the operation definition. This name should be usable as an identifier for the module by machine processing applications such as code generation. */
    name?: string;
    /** A short, descriptive, user-friendly title for the operation definition. */
    title?: string;
    /** The status of this operation definition. Enables tracking the life-cycle of the content. */
    status?: Metriport.fhir.OperationDefinitionStatus;
    /** Whether this is an operation or a named query. */
    kind?: Metriport.fhir.OperationDefinitionKind;
    /** A Boolean value to indicate that this operation definition is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage. */
    experimental?: boolean;
    /** The date (and optionally time) when the operation definition was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the operation definition changes. */
    date?: Metriport.fhir.DateTime;
    /** The name of the organization or individual that published the operation definition. */
    publisher?: string;
    /** Contact details to assist a user in finding and communicating with the publisher. */
    contact?: Metriport.fhir.ContactDetail[];
    /** A free text natural language description of the operation definition from a consumer's perspective. */
    description?: Metriport.fhir.Markdown;
    /** The content was developed with a focus and intent of supporting the contexts that are listed. These contexts may be general categories (gender, age, ...) or may be references to specific programs (insurance plans, studies, ...) and may be used to assist with indexing and searching for appropriate operation definition instances. */
    useContext?: Metriport.fhir.UsageContext[];
    /** A legal or geographic region in which the operation definition is intended to be used. */
    jurisdiction?: Metriport.fhir.CodeableConcept[];
    /** Explanation of why this operation definition is needed and why it has been designed as it has. */
    purpose?: Metriport.fhir.Markdown;
    /** Whether the operation affects state. Side effects such as producing audit trail entries do not count as 'affecting state'. */
    affectsState?: boolean;
    /** The name used to invoke the operation. */
    code?: Metriport.fhir.Code;
    /** Additional information about how to use this operation or named query. */
    comment?: Metriport.fhir.Markdown;
    /** Indicates that this operation definition is a constraining profile on the base. */
    base?: Metriport.fhir.Canonical;
    /** The types on which this operation can be executed. */
    resource?: Metriport.fhir.Code[];
    /** Indicates whether this operation or named query can be invoked at the system level (e.g. without needing to choose a resource type for the context). */
    system?: boolean;
    /** Indicates whether this operation or named query can be invoked at the resource type level for any given resource type level (e.g. without needing to choose a specific resource id for the context). */
    type?: boolean;
    /** Indicates whether this operation can be invoked on a particular instance of one of the given types. */
    instance?: boolean;
    /** Additional validation information for the in parameters - a single profile that covers all the parameters. The profile is a constraint on the parameters resource as a whole. */
    inputProfile?: Metriport.fhir.Canonical;
    /** Additional validation information for the out parameters - a single profile that covers all the parameters. The profile is a constraint on the parameters resource. */
    outputProfile?: Metriport.fhir.Canonical;
    /** The parameters for the operation/query. */
    parameter?: Metriport.fhir.OperationDefinitionParameter[];
    /** Defines an appropriate combination of parameters to use when invoking this operation, to help code generators when generating overloaded parameter sets for this operation. */
    overload?: Metriport.fhir.OperationDefinitionOverload[];
}
