/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A formally or informally recognized grouping of people or organizations formed for the purpose of achieving some form of collective action. Includes companies, institutions, corporations, departments, community groups, healthcare practice groups, payer/insurer, etc.
 */
export interface Organization extends Metriport.fhir.BaseResource {
    resourceType: "Organization";
    /** Identifier for the organization that is used to identify the organization across multiple disparate systems. */
    identifier?: Metriport.fhir.Identifier[];
    /** Whether the organization's record is still in active use. */
    active?: boolean;
    /** The kind(s) of organization that this is. */
    type?: Metriport.fhir.CodeableConcept[];
    /** A name associated with the organization. */
    name?: string;
    /** A list of alternate names that the organization is known as, or was known as in the past. */
    alias?: string[];
    /** A contact detail for the organization. */
    telecom?: Metriport.fhir.ContactPoint[];
    /** An address for the organization. */
    address?: Metriport.fhir.Address[];
    /** The organization of which this organization forms a part. */
    partOf?: Metriport.fhir.Reference;
    /** Contact for the organization for a certain purpose. */
    contact?: Metriport.fhir.OrganizationContact[];
    /** Technical endpoints providing access to services operated for the organization. */
    endpoint?: Metriport.fhir.Reference[];
}
