/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * This resource is a non-persisted resource used to pass information into and back from an [operation](operations.html). It has no other use, and there is no RESTful endpoint associated with it.
 */
export interface ParametersParameter {
    /** Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces. */
    id?: string;
    /** May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. */
    extension?: Metriport.fhir.Extension[];
    /** May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions. Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself). */
    modifierExtension?: Metriport.fhir.Extension[];
    /** The name of the parameter (reference to the operation definition). */
    name?: string;
    /** If the parameter is a data type. */
    valueBase64Binary?: string;
    /** If the parameter is a data type. */
    valueBoolean?: boolean;
    /** If the parameter is a data type. */
    valueCanonical?: string;
    /** If the parameter is a data type. */
    valueCode?: string;
    /** If the parameter is a data type. */
    valueDate?: string;
    /** If the parameter is a data type. */
    valueDateTime?: string;
    /** If the parameter is a data type. */
    valueDecimal?: number;
    /** If the parameter is a data type. */
    valueId?: string;
    /** If the parameter is a data type. */
    valueInstant?: string;
    /** If the parameter is a data type. */
    valueInteger?: number;
    /** If the parameter is a data type. */
    valueMarkdown?: string;
    /** If the parameter is a data type. */
    valueOid?: string;
    /** If the parameter is a data type. */
    valuePositiveInt?: number;
    /** If the parameter is a data type. */
    valueString?: string;
    /** If the parameter is a data type. */
    valueTime?: string;
    /** If the parameter is a data type. */
    valueUnsignedInt?: number;
    /** If the parameter is a data type. */
    valueUri?: string;
    /** If the parameter is a data type. */
    valueUrl?: string;
    /** If the parameter is a data type. */
    valueUuid?: string;
    /** If the parameter is a data type. */
    valueAddress?: Metriport.fhir.Address;
    /** If the parameter is a data type. */
    valueAge?: Metriport.fhir.Age;
    /** If the parameter is a data type. */
    valueAnnotation?: Metriport.fhir.Annotation;
    /** If the parameter is a data type. */
    valueAttachment?: Metriport.fhir.Attachment;
    /** If the parameter is a data type. */
    valueCodeableConcept?: Metriport.fhir.CodeableConcept;
    /** If the parameter is a data type. */
    valueCoding?: Metriport.fhir.Coding;
    /** If the parameter is a data type. */
    valueContactPoint?: Metriport.fhir.ContactPoint;
    /** If the parameter is a data type. */
    valueCount?: Metriport.fhir.Count;
    /** If the parameter is a data type. */
    valueDistance?: Metriport.fhir.Distance;
    /** If the parameter is a data type. */
    valueDuration?: Metriport.fhir.Duration;
    /** If the parameter is a data type. */
    valueHumanName?: Metriport.fhir.HumanName;
    /** If the parameter is a data type. */
    valueIdentifier?: Metriport.fhir.Identifier;
    /** If the parameter is a data type. */
    valueMoney?: Metriport.fhir.Money;
    /** If the parameter is a data type. */
    valuePeriod?: Metriport.fhir.Period;
    /** If the parameter is a data type. */
    valueQuantity?: Metriport.fhir.Quantity;
    /** If the parameter is a data type. */
    valueRange?: Metriport.fhir.Range;
    /** If the parameter is a data type. */
    valueRatio?: Metriport.fhir.Ratio;
    /** If the parameter is a data type. */
    valueReference?: Metriport.fhir.Reference;
    /** If the parameter is a data type. */
    valueSampledData?: Metriport.fhir.SampledData;
    /** If the parameter is a data type. */
    valueSignature?: Metriport.fhir.Signature;
    /** If the parameter is a data type. */
    valueTiming?: Metriport.fhir.Timing;
    /** If the parameter is a data type. */
    valueContactDetail?: Metriport.fhir.ContactDetail;
    /** If the parameter is a data type. */
    valueContributor?: Metriport.fhir.Contributor;
    /** If the parameter is a data type. */
    valueDataRequirement?: Metriport.fhir.DataRequirement;
    /** If the parameter is a data type. */
    valueExpression?: Metriport.fhir.Expression;
    /** If the parameter is a data type. */
    valueParameterDefinition?: Metriport.fhir.ParameterDefinition;
    /** If the parameter is a data type. */
    valueRelatedArtifact?: Metriport.fhir.RelatedArtifact;
    /** If the parameter is a data type. */
    valueTriggerDefinition?: Metriport.fhir.TriggerDefinition;
    /** If the parameter is a data type. */
    valueUsageContext?: Metriport.fhir.UsageContext;
    /** If the parameter is a data type. */
    valueDosage?: Metriport.fhir.Dosage;
    /** If the parameter is a data type. */
    valueMeta?: Metriport.fhir.Meta;
    /** If the parameter is a whole resource. */
    resource?: unknown;
    /** A named part of a multi-part parameter. */
    part?: Metriport.fhir.ParametersParameter[];
}
