/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Administrative Gender - the gender that the patient is considered to have for administration and record keeping purposes.
 */
export type PatientGender = "male" | "female" | "other" | "unknown";

export const PatientGender = {
    Male: "male",
    Female: "female",
    Other: "other",
    Unknown: "unknown",
} as const;
