/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The business purpose of the note text.
 */
export type PaymentReconciliationProcessNoteType = "display" | "print" | "printoper";

export const PaymentReconciliationProcessNoteType = {
    Display: "display",
    Print: "print",
    Printoper: "printoper",
} as const;
