/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Administrative Gender.
 */
export type PersonGender = "male" | "female" | "other" | "unknown";

export const PersonGender = {
    Male: "male",
    Female: "female",
    Other: "other",
    Unknown: "unknown",
} as const;
