/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Defines the selection behavior for the action and its children.
 */
export type PlanDefinitionActionSelectionBehavior =
    | "any"
    | "all"
    | "all-or-none"
    | "exactly-one"
    | "at-most-one"
    | "one-or-more";

export const PlanDefinitionActionSelectionBehavior = {
    Any: "any",
    All: "all",
    AllOrNone: "all-or-none",
    ExactlyOne: "exactly-one",
    AtMostOne: "at-most-one",
    OneOrMore: "one-or-more",
} as const;
