/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * This resource allows for the definition of various types of plans as a sharable, consumable, and executable artifact. The resource is general enough to support the description of a broad range of clinical artifacts such as clinical decision support rules, order sets and protocols.
 */
export interface PlanDefinition extends Metriport.fhir.BaseResource {
    resourceType: "PlanDefinition";
    /** An absolute URI that is used to identify this plan definition when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which at which an authoritative instance of this plan definition is (or will be) published. This URL can be the target of a canonical reference. It SHALL remain the same when the plan definition is stored on different servers. */
    url?: Metriport.fhir.Uri;
    /** A formal identifier that is used to identify this plan definition when it is represented in other formats, or referenced in a specification, model, design or an instance. */
    identifier?: Metriport.fhir.Identifier[];
    /** The identifier that is used to identify this version of the plan definition when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the plan definition author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence. To provide a version consistent with the Decision Support Service specification, use the format Major.Minor.Revision (e.g. 1.0.0). For more information on versioning knowledge assets, refer to the Decision Support Service specification. Note that a version is required for non-experimental active artifacts. */
    version?: string;
    /** A natural language name identifying the plan definition. This name should be usable as an identifier for the module by machine processing applications such as code generation. */
    name?: string;
    /** A short, descriptive, user-friendly title for the plan definition. */
    title?: string;
    /** An explanatory or alternate title for the plan definition giving additional information about its content. */
    subtitle?: string;
    /** A high-level category for the plan definition that distinguishes the kinds of systems that would be interested in the plan definition. */
    type?: Metriport.fhir.CodeableConcept;
    /** The status of this plan definition. Enables tracking the life-cycle of the content. */
    status?: Metriport.fhir.PlanDefinitionStatus;
    /** A Boolean value to indicate that this plan definition is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage. */
    experimental?: boolean;
    /** A code or group definition that describes the intended subject of the plan definition. */
    subjectCodeableConcept?: Metriport.fhir.CodeableConcept;
    /** A code or group definition that describes the intended subject of the plan definition. */
    subjectReference?: Metriport.fhir.Reference;
    /** The date (and optionally time) when the plan definition was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the plan definition changes. */
    date?: Metriport.fhir.DateTime;
    /** The name of the organization or individual that published the plan definition. */
    publisher?: string;
    /** Contact details to assist a user in finding and communicating with the publisher. */
    contact?: Metriport.fhir.ContactDetail[];
    /** A free text natural language description of the plan definition from a consumer's perspective. */
    description?: Metriport.fhir.Markdown;
    /** The content was developed with a focus and intent of supporting the contexts that are listed. These contexts may be general categories (gender, age, ...) or may be references to specific programs (insurance plans, studies, ...) and may be used to assist with indexing and searching for appropriate plan definition instances. */
    useContext?: Metriport.fhir.UsageContext[];
    /** A legal or geographic region in which the plan definition is intended to be used. */
    jurisdiction?: Metriport.fhir.CodeableConcept[];
    /** Explanation of why this plan definition is needed and why it has been designed as it has. */
    purpose?: Metriport.fhir.Markdown;
    /** A detailed description of how the plan definition is used from a clinical perspective. */
    usage?: string;
    /** A copyright statement relating to the plan definition and/or its contents. Copyright statements are generally legal restrictions on the use and publishing of the plan definition. */
    copyright?: Metriport.fhir.Markdown;
    /** The date on which the resource content was approved by the publisher. Approval happens once when the content is officially approved for usage. */
    approvalDate?: string;
    /** The date on which the resource content was last reviewed. Review happens periodically after approval but does not change the original approval date. */
    lastReviewDate?: string;
    /** The period during which the plan definition content was or is planned to be in active use. */
    effectivePeriod?: Metriport.fhir.Period;
    /** Descriptive topics related to the content of the plan definition. Topics provide a high-level categorization of the definition that can be useful for filtering and searching. */
    topic?: Metriport.fhir.CodeableConcept[];
    /** An individiual or organization primarily involved in the creation and maintenance of the content. */
    author?: Metriport.fhir.ContactDetail[];
    /** An individual or organization primarily responsible for internal coherence of the content. */
    editor?: Metriport.fhir.ContactDetail[];
    /** An individual or organization primarily responsible for review of some aspect of the content. */
    reviewer?: Metriport.fhir.ContactDetail[];
    /** An individual or organization responsible for officially endorsing the content for use in some setting. */
    endorser?: Metriport.fhir.ContactDetail[];
    /** Related artifacts such as additional documentation, justification, or bibliographic references. */
    relatedArtifact?: Metriport.fhir.RelatedArtifact[];
    /** A reference to a Library resource containing any formal logic used by the plan definition. */
    library?: Metriport.fhir.Canonical[];
    /** Goals that describe what the activities within the plan are intended to achieve. For example, weight loss, restoring an activity of daily living, obtaining herd immunity via immunization, meeting a process improvement objective, etc. */
    goal?: Metriport.fhir.PlanDefinitionGoal[];
    /** An action or group of actions to be taken as part of the plan. */
    action?: Metriport.fhir.PlanDefinitionAction[];
}
