/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A person who is directly or indirectly involved in the provisioning of healthcare.
 */
export interface Practitioner extends Metriport.fhir.BaseResource {
    resourceType: "Practitioner";
    /** An identifier that applies to this person in this role. */
    identifier?: Metriport.fhir.Identifier[];
    /** Whether this practitioner's record is in active use. */
    active?: boolean;
    /** The name(s) associated with the practitioner. */
    name?: Metriport.fhir.HumanName[];
    /** A contact detail for the practitioner, e.g. a telephone number or an email address. */
    telecom?: Metriport.fhir.ContactPoint[];
    /**
     * Address(es) of the practitioner that are not role specific (typically home address).
     * Work addresses are not typically entered in this property as they are usually role dependent.
     */
    address?: Metriport.fhir.Address[];
    /** Administrative Gender - the gender that the person is considered to have for administration and record keeping purposes. */
    gender?: Metriport.fhir.PractitionerGender;
    /** The date of birth for the practitioner. */
    birthDate?: string;
    /** Image of the person. */
    photo?: Metriport.fhir.Attachment[];
    /** The official certifications, training, and licenses that authorize or otherwise pertain to the provision of care by the practitioner. For example, a medical license issued by a medical board authorizing the practitioner to practice medicine within a certian locality. */
    qualification?: Metriport.fhir.PractitionerQualification[];
    /** A language the practitioner can use in patient communication. */
    communication?: Metriport.fhir.CodeableConcept[];
}
