/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * User options that control the display of the application.
 */
export interface ProjectMembershipAccessParameter {
    /** The unique name of the parameter. */
    name: Metriport.fhir.Code;
    /** Value of the parameter - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list). */
    valueString?: string;
    /** Value of the parameter - must be one of a constrained set of the data types (see [Extensibility](extensibility.html) for a list). */
    valueReference?: Metriport.fhir.Reference;
}
