/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Web application or web site that is associated with the project.
 */
export interface ProjectSite {
    /** Friendly name that will make it easy for you to identify the site in the future. */
    name: string;
    /** The list of domain names associated with the site. User authentication will be restricted to the domains you enter here, plus any subdomains. In other words, a registration for example.com also registers subdomain.example.com. A valid domain requires a host and must not include any path, port, query or fragment. */
    domain: string[];
    /** The publicly visible Google Client ID for the site. This is used to authenticate users with Google. This value is available in the Google Developer Console. */
    googleClientId?: string;
    /** The private Google Client Secret for the site. This value is available in the Google Developer Console. */
    googleClientSecret?: string;
    /** The publicly visible reCAPTCHA site key. This value is generated when you create a new reCAPTCHA site in the reCAPTCHA admin console. Use this site key in the HTML code your site serves to users. */
    recaptchaSiteKey?: string;
    /** The private reCAPTCHA secret key. This value is generated when you create a new reCAPTCHA site in the reCAPTCHA admin console. Use this secret key for communication between your site and reCAPTCHA. */
    recaptchaSecretKey?: string;
}
