/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ProjectFeaturesItem = "bots" | "cron" | "email" | "google-auth-required" | "graphql-introspection";

export const ProjectFeaturesItem = {
    Bots: "bots",
    Cron: "cron",
    Email: "email",
    GoogleAuthRequired: "google-auth-required",
    GraphqlIntrospection: "graphql-introspection",
} as const;
