/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * How the entity was used during the activity.
 */
export type ProvenanceEntityRole = "derivation" | "revision" | "quotation" | "source" | "removal";

export const ProvenanceEntityRole = {
    Derivation: "derivation",
    Revision: "revision",
    Quotation: "quotation",
    Source: "source",
    Removal: "removal",
} as const;
