/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A structured set of questions intended to guide the collection of answers from end-users. Questionnaires provide detailed control over order, presentation, phraseology and grouping to allow coherent, consistent data collection.
 */
export interface Questionnaire extends Metriport.fhir.BaseResource {
    resourceType: "Questionnaire";
    /** An absolute URI that is used to identify this questionnaire when it is referenced in a specification, model, design or an instance; also called its canonical identifier. This SHOULD be globally unique and SHOULD be a literal address at which at which an authoritative instance of this questionnaire is (or will be) published. This URL can be the target of a canonical reference. It SHALL remain the same when the questionnaire is stored on different servers. */
    url?: Metriport.fhir.Uri;
    /** A formal identifier that is used to identify this questionnaire when it is represented in other formats, or referenced in a specification, model, design or an instance. */
    identifier?: Metriport.fhir.Identifier[];
    /** The identifier that is used to identify this version of the questionnaire when it is referenced in a specification, model, design or instance. This is an arbitrary value managed by the questionnaire author and is not expected to be globally unique. For example, it might be a timestamp (e.g. yyyymmdd) if a managed version is not available. There is also no expectation that versions can be placed in a lexicographical sequence. */
    version?: string;
    /** A natural language name identifying the questionnaire. This name should be usable as an identifier for the module by machine processing applications such as code generation. */
    name?: string;
    /** A short, descriptive, user-friendly title for the questionnaire. */
    title?: string;
    /** The URL of a Questionnaire that this Questionnaire is based on. */
    derivedFrom?: Metriport.fhir.Canonical[];
    /** The status of this questionnaire. Enables tracking the life-cycle of the content. */
    status?: Metriport.fhir.QuestionnaireStatus;
    /** A Boolean value to indicate that this questionnaire is authored for testing purposes (or education/evaluation/marketing) and is not intended to be used for genuine usage. */
    experimental?: boolean;
    /** The types of subjects that can be the subject of responses created for the questionnaire. */
    subjectType?: Metriport.fhir.Code[];
    /** The date (and optionally time) when the questionnaire was published. The date must change when the business version changes and it must change if the status code changes. In addition, it should change when the substantive content of the questionnaire changes. */
    date?: Metriport.fhir.DateTime;
    /** The name of the organization or individual that published the questionnaire. */
    publisher?: string;
    /** Contact details to assist a user in finding and communicating with the publisher. */
    contact?: Metriport.fhir.ContactDetail[];
    /** A free text natural language description of the questionnaire from a consumer's perspective. */
    description?: Metriport.fhir.Markdown;
    /** The content was developed with a focus and intent of supporting the contexts that are listed. These contexts may be general categories (gender, age, ...) or may be references to specific programs (insurance plans, studies, ...) and may be used to assist with indexing and searching for appropriate questionnaire instances. */
    useContext?: Metriport.fhir.UsageContext[];
    /** A legal or geographic region in which the questionnaire is intended to be used. */
    jurisdiction?: Metriport.fhir.CodeableConcept[];
    /** Explanation of why this questionnaire is needed and why it has been designed as it has. */
    purpose?: Metriport.fhir.Markdown;
    /** A copyright statement relating to the questionnaire and/or its contents. Copyright statements are generally legal restrictions on the use and publishing of the questionnaire. */
    copyright?: Metriport.fhir.Markdown;
    /** The date on which the resource content was approved by the publisher. Approval happens once when the content is officially approved for usage. */
    approvalDate?: string;
    /** The date on which the resource content was last reviewed. Review happens periodically after approval but does not change the original approval date. */
    lastReviewDate?: string;
    /** The period during which the questionnaire content was or is planned to be in active use. */
    effectivePeriod?: Metriport.fhir.Period;
    /** An identifier for this question or group of questions in a particular terminology such as LOINC. */
    code?: Metriport.fhir.Coding[];
    /** A particular question, question grouping or display text that is part of the questionnaire. */
    item?: Metriport.fhir.QuestionnaireItem[];
}
