/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of questionnaire item this is - whether text for display, a grouping of other items or a particular type of data to be captured (string, integer, coded choice, etc.).
 */
export type QuestionnaireItemType =
    | "group"
    | "display"
    | "boolean"
    | "decimal"
    | "integer"
    | "date"
    | "dateTime"
    | "time"
    | "string"
    | "text"
    | "url"
    | "choice"
    | "open-choice"
    | "attachment"
    | "reference"
    | "quantity";

export const QuestionnaireItemType = {
    Group: "group",
    Display: "display",
    Boolean: "boolean",
    Decimal: "decimal",
    Integer: "integer",
    Date: "date",
    DateTime: "dateTime",
    Time: "time",
    String: "string",
    Text: "text",
    Url: "url",
    Choice: "choice",
    OpenChoice: "open-choice",
    Attachment: "attachment",
    Reference: "reference",
    Quantity: "quantity",
} as const;
