/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Specifies the criteria by which the question is enabled.
 */
export type QuestionnaireEnableWhenOperator = "exists" | "=" | "!=" | ">" | "<" | ">=" | "<=";

export const QuestionnaireEnableWhenOperator = {
    Exists: "exists",
    Equal: "=",
    NotEqual: "!=",
    GreaterThan: ">",
    LessThan: "<",
    GreaterThanOrEqualTo: ">=",
    LessThanOrEqualTo: "<=",
} as const;
