/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A structured set of questions intended to guide the collection of answers from end-users. Questionnaires provide detailed control over order, presentation, phraseology and grouping to allow coherent, consistent data collection.
 */
export interface QuestionnaireItem {
    /** Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces. */
    id?: string;
    /** May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. */
    extension?: Metriport.fhir.Extension[];
    /** May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions. Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself). */
    modifierExtension?: Metriport.fhir.Extension[];
    /** An identifier that is unique within the Questionnaire allowing linkage to the equivalent item in a QuestionnaireResponse resource. */
    linkId?: string;
    /** This element is a URI that refers to an [[[ElementDefinition]]] that provides information about this item, including information that might otherwise be included in the instance of the Questionnaire resource. A detailed description of the construction of the URI is shown in Comments, below. If this element is present then the following element values MAY be derived from the Element Definition if the corresponding elements of this Questionnaire resource instance have no value: _ code (ElementDefinition.code) _ type (ElementDefinition.type) _ required (ElementDefinition.min) _ repeats (ElementDefinition.max) _ maxLength (ElementDefinition.maxLength) _ answerValueSet (ElementDefinition.binding) \* options (ElementDefinition.binding). */
    definition?: Metriport.fhir.Uri;
    /** A terminology code that corresponds to this group or question (e.g. a code from LOINC, which defines many questions and answers). */
    code?: Metriport.fhir.Coding[];
    /** A short label for a particular group, question or set of display text within the questionnaire used for reference by the individual completing the questionnaire. */
    prefix?: string;
    /** The name of a section, the text of a question or text content for a display item. */
    text?: string;
    /** The type of questionnaire item this is - whether text for display, a grouping of other items or a particular type of data to be captured (string, integer, coded choice, etc.). */
    type?: Metriport.fhir.QuestionnaireItemType;
    /** A constraint indicating that this item should only be enabled (displayed/allow answers to be captured) when the specified condition is true. */
    enableWhen?: Metriport.fhir.QuestionnaireEnableWhen[];
    /** Controls how multiple enableWhen values are interpreted - whether all or any must be true. */
    enableBehavior?: Metriport.fhir.QuestionnaireItemEnableBehavior;
    /** An indication, if true, that the item must be present in a "completed" QuestionnaireResponse. If false, the item may be skipped when answering the questionnaire. */
    required?: boolean;
    /** An indication, if true, that the item may occur multiple times in the response, collecting multiple answers for questions or multiple sets of answers for groups. */
    repeats?: boolean;
    /** An indication, when true, that the value cannot be changed by a human respondent to the Questionnaire. */
    readOnly?: boolean;
    /** The maximum number of characters that are permitted in the answer to be considered a "valid" QuestionnaireResponse. */
    maxLength?: number;
    /** A reference to a value set containing a list of codes representing permitted answers for a "choice" or "open-choice" question. */
    answerValueSet?: Metriport.fhir.Canonical;
    /** One of the permitted answers for a "choice" or "open-choice" question. */
    answerOption?: Metriport.fhir.QuestionnaireAnswerOption[];
    /** One or more values that should be pre-populated in the answer when initially rendering the questionnaire for user input. */
    initial?: Metriport.fhir.QuestionnaireInitial[];
    /** Text, questions and other groups to be nested beneath a question or group. */
    item?: Metriport.fhir.QuestionnaireItem[];
}
