/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A group of related requests that can be used to capture intended activities that have inter-dependencies such as "give this medication after that one".
 */
export interface RequestGroupAction {
    /** Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces. */
    id?: string;
    /** May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. */
    extension?: Metriport.fhir.Extension[];
    /** May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions. Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself). */
    modifierExtension?: Metriport.fhir.Extension[];
    /** A user-visible prefix for the action. */
    prefix?: string;
    /** The title of the action displayed to a user. */
    title?: string;
    /** A short description of the action used to provide a summary to display to the user. */
    description?: string;
    /** A text equivalent of the action to be performed. This provides a human-interpretable description of the action when the definition is consumed by a system that might not be capable of interpreting it dynamically. */
    textEquivalent?: string;
    /** Indicates how quickly the action should be addressed with respect to other actions. */
    priority?: Metriport.fhir.Code;
    /** A code that provides meaning for the action or action group. For example, a section may have a LOINC code for a section of a documentation template. */
    code?: Metriport.fhir.CodeableConcept[];
    /** Didactic or other informational resources associated with the action that can be provided to the CDS recipient. Information resources can include inline text commentary and links to web resources. */
    documentation?: Metriport.fhir.RelatedArtifact[];
    /** An expression that describes applicability criteria, or start/stop conditions for the action. */
    condition?: Metriport.fhir.RequestGroupCondition[];
    /** A relationship to another action such as "before" or "30-60 minutes after start of". */
    relatedAction?: Metriport.fhir.RequestGroupRelatedAction[];
    /** An optional value describing when the action should be performed. */
    timingDateTime?: string;
    /** An optional value describing when the action should be performed. */
    timingAge?: Metriport.fhir.Age;
    /** An optional value describing when the action should be performed. */
    timingPeriod?: Metriport.fhir.Period;
    /** An optional value describing when the action should be performed. */
    timingDuration?: Metriport.fhir.Duration;
    /** An optional value describing when the action should be performed. */
    timingRange?: Metriport.fhir.Range;
    /** An optional value describing when the action should be performed. */
    timingTiming?: Metriport.fhir.Timing;
    /** The participant that should perform or be responsible for this action. */
    participant?: Metriport.fhir.Reference[];
    /** The type of action to perform (create, update, remove). */
    type?: Metriport.fhir.CodeableConcept;
    /** Defines the grouping behavior for the action and its children. */
    groupingBehavior?: Metriport.fhir.Code;
    /** Defines the selection behavior for the action and its children. */
    selectionBehavior?: Metriport.fhir.Code;
    /** Defines expectations around whether an action is required. */
    requiredBehavior?: Metriport.fhir.Code;
    /** Defines whether the action should usually be preselected. */
    precheckBehavior?: Metriport.fhir.Code;
    /** Defines whether the action can be selected multiple times. */
    cardinalityBehavior?: Metriport.fhir.Code;
    /** The resource that is the target of the action (e.g. CommunicationRequest). */
    resource?: Metriport.fhir.Reference;
    /** Sub actions. */
    action?: Metriport.fhir.RequestGroupAction[];
}
