/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates how elements are aggregated within the study effective period.
 */
export type ResearchElementDefinitionCharacteristicStudyEffectiveGroupMeasure =
    | "mean"
    | "median"
    | "mean-of-mean"
    | "mean-of-median"
    | "median-of-mean"
    | "median-of-median";

export const ResearchElementDefinitionCharacteristicStudyEffectiveGroupMeasure = {
    Mean: "mean",
    Median: "median",
    MeanOfMean: "mean-of-mean",
    MeanOfMedian: "mean-of-median",
    MedianOfMean: "median-of-mean",
    MedianOfMedian: "median-of-median",
} as const;
