/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current state of the subject.
 */
export type ResearchSubjectStatus =
    | "candidate"
    | "eligible"
    | "follow-up"
    | "ineligible"
    | "not-registered"
    | "off-study"
    | "on-study"
    | "on-study-intervention"
    | "on-study-observation"
    | "pending-on-study"
    | "potential-candidate"
    | "screening"
    | "withdrawn";

export const ResearchSubjectStatus = {
    Candidate: "candidate",
    Eligible: "eligible",
    FollowUp: "follow-up",
    Ineligible: "ineligible",
    NotRegistered: "not-registered",
    OffStudy: "off-study",
    OnStudy: "on-study",
    OnStudyIntervention: "on-study-intervention",
    OnStudyObservation: "on-study-observation",
    PendingOnStudy: "pending-on-study",
    PotentialCandidate: "potential-candidate",
    Screening: "screening",
    Withdrawn: "withdrawn",
} as const;
