/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A process where a researcher or organization plans and then executes a series of steps intended to increase the field of healthcare-related knowledge. This includes studies of safety, efficacy, comparative effectiveness and other information about medications, devices, therapies and other interventional and investigative techniques. A ResearchStudy involves the gathering of information about human or animal subjects.
 */
export interface ResearchStudy extends Metriport.fhir.BaseResource {
    resourceType: "ResearchStudy";
    /** Identifiers assigned to this research study by the sponsor or other systems. */
    identifier?: Metriport.fhir.Identifier[];
    /** A short, descriptive user-friendly label for the study. */
    title?: string;
    /** The set of steps expected to be performed as part of the execution of the study. */
    protocol?: Metriport.fhir.Reference[];
    /** A larger research study of which this particular study is a component or step. */
    partOf?: Metriport.fhir.Reference[];
    /** The current state of the study. */
    status?: Metriport.fhir.ResearchStudyStatus;
    /** The type of study based upon the intent of the study's activities. A classification of the intent of the study. */
    primaryPurposeType?: Metriport.fhir.CodeableConcept;
    /** The stage in the progression of a therapy from initial experimental use in humans in clinical trials to post-market evaluation. */
    phase?: Metriport.fhir.CodeableConcept;
    /** Codes categorizing the type of study such as investigational vs. observational, type of blinding, type of randomization, safety vs. efficacy, etc. */
    category?: Metriport.fhir.CodeableConcept[];
    /** The medication(s), food(s), therapy(ies), device(s) or other concerns or interventions that the study is seeking to gain more information about. */
    focus?: Metriport.fhir.CodeableConcept[];
    /** The condition that is the focus of the study. For example, In a study to examine risk factors for Lupus, might have as an inclusion criterion "healthy volunteer", but the target condition code would be a Lupus SNOMED code. */
    condition?: Metriport.fhir.CodeableConcept[];
    /** Contact details to assist a user in learning more about or engaging with the study. */
    contact?: Metriport.fhir.ContactDetail[];
    /** Citations, references and other related documents. */
    relatedArtifact?: Metriport.fhir.RelatedArtifact[];
    /** Key terms to aid in searching for or filtering the study. */
    keyword?: Metriport.fhir.CodeableConcept[];
    /** Indicates a country, state or other region where the study is taking place. */
    location?: Metriport.fhir.CodeableConcept[];
    /** A full description of how the study is being conducted. */
    description?: Metriport.fhir.Markdown;
    /** Reference to a Group that defines the criteria for and quantity of subjects participating in the study. E.g. " 200 female Europeans between the ages of 20 and 45 with early onset diabetes". */
    enrollment?: Metriport.fhir.Reference[];
    /** Identifies the start date and the expected (or actual, depending on status) end date for the study. */
    period?: Metriport.fhir.Period;
    /** An organization that initiates the investigation and is legally responsible for the study. */
    sponsor?: Metriport.fhir.Reference;
    /** A researcher in a study who oversees multiple aspects of the study, such as concept development, protocol writing, protocol submission for IRB approval, participant recruitment, informed consent, data collection, analysis, interpretation and presentation. */
    principalInvestigator?: Metriport.fhir.Reference;
    /** A facility in which study activities are conducted. */
    site?: Metriport.fhir.Reference[];
    /** A description and/or code explaining the premature termination of the study. */
    reasonStopped?: Metriport.fhir.CodeableConcept;
    /** Comments made about the study by the performer, subject or other participants. */
    note?: Metriport.fhir.Annotation[];
    /** Describes an expected sequence of events for one of the participants of a study. E.g. Exposure to drug A, wash-out, exposure to drug B, wash-out, follow-up. */
    arm?: Metriport.fhir.ResearchStudyArm[];
    /** A goal that the study is aiming to achieve in terms of a scientific question to be answered by the analysis of data collected during the study. */
    objective?: Metriport.fhir.ResearchStudyObjective[];
}
