/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current state of the study.
 */
export type ResearchStudyStatus =
    | "active"
    | "administratively-completed"
    | "approved"
    | "closed-to-accrual"
    | "closed-to-accrual-and-intervention"
    | "completed"
    | "disapproved"
    | "in-review"
    | "temporarily-closed-to-accrual"
    | "temporarily-closed-to-accrual-and-intervention"
    | "withdrawn";

export const ResearchStudyStatus = {
    Active: "active",
    AdministrativelyCompleted: "administratively-completed",
    Approved: "approved",
    ClosedToAccrual: "closed-to-accrual",
    ClosedToAccrualAndIntervention: "closed-to-accrual-and-intervention",
    Completed: "completed",
    Disapproved: "disapproved",
    InReview: "in-review",
    TemporarilyClosedToAccrual: "temporarily-closed-to-accrual",
    TemporarilyClosedToAccrualAndIntervention: "temporarily-closed-to-accrual-and-intervention",
    Withdrawn: "withdrawn",
} as const;
