/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A physical entity which is the primary unit of operational and/or administrative interest in a study.
 */
export interface ResearchSubject extends Metriport.fhir.BaseResource {
    resourceType: "ResearchSubject";
    /** Identifiers assigned to this research subject for a study. */
    identifier?: Metriport.fhir.Identifier[];
    /** The current state of the subject. */
    status?: Metriport.fhir.ResearchSubjectStatus;
    /** The dates the subject began and ended their participation in the study. */
    period?: Metriport.fhir.Period;
    /** Reference to the study the subject is participating in. */
    study: Metriport.fhir.Reference;
    /** The record of the person or animal who is involved in the study. */
    individual: Metriport.fhir.Reference;
    /** The name of the arm in the study the subject is expected to follow as part of this study. */
    assignedArm?: string;
    /** The name of the arm in the study the subject actually followed as part of this study. */
    actualArm?: string;
    /** A record of the patient's informed agreement to participate in the study. */
    consent?: Metriport.fhir.Reference;
}
