/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A container for slots of time that may be available for booking appointments.
 */
export interface Schedule extends Metriport.fhir.BaseResource {
    resourceType: "Schedule";
    /** External Ids for this item. */
    identifier?: Metriport.fhir.Identifier[];
    /** Whether this schedule record is in active use or should not be used (such as was entered in error). */
    active?: boolean;
    /** A broad categorization of the service that is to be performed during this appointment. */
    serviceCategory?: Metriport.fhir.CodeableConcept[];
    /** The specific service that is to be performed during this appointment. */
    serviceType?: Metriport.fhir.CodeableConcept[];
    /** The specialty of a practitioner that would be required to perform the service requested in this appointment. */
    specialty?: Metriport.fhir.CodeableConcept[];
    /** Slots that reference this schedule resource provide the availability details to these referenced resource(s). */
    actor: Metriport.fhir.Reference[];
    /** The period of time that the slots that reference this Schedule resource cover (even if none exist). These cover the amount of time that an organization's planning horizon; the interval for which they are currently accepting appointments. This does not define a "template" for planning outside these dates. */
    planningHorizon?: Metriport.fhir.Period;
    /** Comments on the availability to describe any extended information. Such as custom constraints on the slots that may be associated. */
    comment?: string;
}
