/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SearchParameterModifierItem =
    | "missing"
    | "exact"
    | "contains"
    | "not"
    | "text"
    | "in"
    | "not-in"
    | "below"
    | "above"
    | "type"
    | "identifier"
    | "ofType";

export const SearchParameterModifierItem = {
    Missing: "missing",
    Exact: "exact",
    Contains: "contains",
    Not: "not",
    Text: "text",
    In: "in",
    NotIn: "not-in",
    Below: "below",
    Above: "above",
    Type: "type",
    Identifier: "identifier",
    OfType: "ofType",
} as const;
