/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A slot of time on a schedule that may be available for booking appointments.
 */
export interface Slot extends Metriport.fhir.BaseResource {
    resourceType: "Slot";
    /** External Ids for this item. */
    identifier?: Metriport.fhir.Identifier[];
    /** A broad categorization of the service that is to be performed during this appointment. */
    serviceCategory?: Metriport.fhir.CodeableConcept[];
    /** The type of appointments that can be booked into this slot (ideally this would be an identifiable service - which is at a location, rather than the location itself). If provided then this overrides the value provided on the availability resource. */
    serviceType?: Metriport.fhir.CodeableConcept[];
    /** The specialty of a practitioner that would be required to perform the service requested in this appointment. */
    specialty?: Metriport.fhir.CodeableConcept[];
    /** The style of appointment or patient that may be booked in the slot (not service type). */
    appointmentType?: Metriport.fhir.CodeableConcept;
    /** The schedule resource that this slot defines an interval of status information. */
    schedule: Metriport.fhir.Reference;
    /** busy | free | busy-unavailable | busy-tentative | entered-in-error. */
    status?: Metriport.fhir.SlotStatus;
    /** Date/Time that the slot is to begin. */
    start?: Metriport.fhir.Instant;
    /** Date/Time that the slot is to conclude. */
    end?: Metriport.fhir.Instant;
    /** This slot has already been overbooked, appointments are unlikely to be accepted for this time. */
    overbooked?: boolean;
    /** Comments on the slot to describe any extended information. Such as custom constraints on the slot. */
    comment?: string;
}
