/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The availability of the specimen.
 */
export type SpecimenStatus = "available" | "unavailable" | "unsatisfactory" | "entered-in-error";

export const SpecimenStatus = {
    Available: "available",
    Unavailable: "unavailable",
    Unsatisfactory: "unsatisfactory",
    EnteredInError: "entered-in-error",
} as const;
