/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A sample to be used for analysis.
 */
export interface Specimen extends Metriport.fhir.BaseResource {
    resourceType: "Specimen";
    /** Id for specimen. */
    identifier?: Metriport.fhir.Identifier[];
    /** The identifier assigned by the lab when accessioning specimen(s). This is not necessarily the same as the specimen identifier, depending on local lab procedures. */
    accessionIdentifier?: Metriport.fhir.Identifier;
    /** The availability of the specimen. */
    status?: Metriport.fhir.SpecimenStatus;
    /** The kind of material that forms the specimen. */
    type?: Metriport.fhir.CodeableConcept;
    /** Where the specimen came from. This may be from patient(s), from a location (e.g., the source of an environmental sample), or a sampling of a substance or a device. */
    subject?: Metriport.fhir.Reference;
    /** Time when specimen was received for processing or testing. */
    receivedTime?: Metriport.fhir.DateTime;
    /** Reference to the parent (source) specimen which is used when the specimen was either derived from or a component of another specimen. */
    parent?: Metriport.fhir.Reference[];
    /** Details concerning a service request that required a specimen to be collected. */
    request?: Metriport.fhir.Reference[];
    /** Details concerning the specimen collection. */
    collection?: Metriport.fhir.SpecimenCollection;
    /** Details concerning processing and processing steps for the specimen. */
    processing?: Metriport.fhir.SpecimenProcessing[];
    /** The container holding the specimen. The recursive nature of containers; i.e. blood in tube in tray in rack is not addressed here. */
    container?: Metriport.fhir.SpecimenContainer[];
    /** A mode or state of being that describes the nature of the specimen. */
    condition?: Metriport.fhir.CodeableConcept[];
    /** To communicate any details or issues about the specimen or during the specimen collection. (for example: broken vial, sent with patient, frozen). */
    note?: Metriport.fhir.Annotation[];
}
