/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * A sample to be used for analysis.
 */
export interface SpecimenContainer {
    /** Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces. */
    id?: string;
    /** May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. */
    extension?: Metriport.fhir.Extension[];
    /** May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions. Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself). */
    modifierExtension?: Metriport.fhir.Extension[];
    /** Id for container. There may be multiple; a manufacturer's bar code, lab assigned identifier, etc. The container ID may differ from the specimen id in some circumstances. */
    identifier?: Metriport.fhir.Identifier[];
    /** Textual description of the container. */
    description?: string;
    /** The type of container associated with the specimen (e.g. slide, aliquot, etc.). */
    type?: Metriport.fhir.CodeableConcept;
    /** The capacity (volume or other measure) the container may contain. */
    capacity?: Metriport.fhir.Quantity;
    /** The quantity of specimen in the container; may be volume, dimensions, or other appropriate measurements, depending on the specimen type. */
    specimenQuantity?: Metriport.fhir.Quantity;
    /** Introduced substance to preserve, maintain or enhance the specimen. Examples: Formalin, Citrate, EDTA. */
    additiveCodeableConcept?: Metriport.fhir.CodeableConcept;
    /** Introduced substance to preserve, maintain or enhance the specimen. Examples: Formalin, Citrate, EDTA. */
    additiveReference?: Metriport.fhir.Reference;
}
