/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * If this is the default rule set to apply for the source type or this combination of types.
 */
export type StructureMapGroupTypeMode = "none" | "types" | "type-and-types";

export const StructureMapGroupTypeMode = {
    None: "none",
    Types: "types",
    TypeAndTypes: "type-and-types",
} as const;
