/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Mode for this instance of data.
 */
export type StructureMapInputMode = "source" | "target";

export const StructureMapInputMode = {
    Source: "source",
    Target: "target",
} as const;
