/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StructureMapTargetListModeItem = "first" | "share" | "last" | "collate";

export const StructureMapTargetListModeItem = {
    First: "first",
    Share: "share",
    Last: "last",
    Collate: "collate",
} as const;
