/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Source material shall capture information on the taxonomic and anatomical origins as well as the fraction of a material that can result in or can be modified to form a substance. This set of data elements shall be used to define polymer substances isolated from biological matrices. Taxonomic and anatomical origins shall be described using a controlled vocabulary as required. This information is captured for naturally derived polymers ( . starch) and structurally diverse substances. For Organisms belonging to the Kingdom Plantae the Substance level defines the fresh material of a single species or infraspecies, the Herbal Drug and the Herbal preparation. For Herbal preparations, the fraction information will be captured at the Substance information level and additional information for herbal extracts will be captured at the Specified Substance Group 1 information level. See for further explanation the Substance Class: Structurally Diverse and the herbal annex.
 */
export interface SubstanceSourceMaterial extends Metriport.fhir.BaseResource {
    resourceType: "SubstanceSourceMaterial";
    /** General high level classification of the source material specific to the origin of the material. */
    sourceMaterialClass?: Metriport.fhir.CodeableConcept;
    /** The type of the source material shall be specified based on a controlled vocabulary. For vaccines, this subclause refers to the class of infectious agent. */
    sourceMaterialType?: Metriport.fhir.CodeableConcept;
    /** The state of the source material when extracted. */
    sourceMaterialState?: Metriport.fhir.CodeableConcept;
    /** The unique identifier associated with the source material parent organism shall be specified. */
    organismId?: Metriport.fhir.Identifier;
    /** The organism accepted Scientific name shall be provided based on the organism taxonomy. */
    organismName?: string;
    /** The parent of the herbal drug Ginkgo biloba, Leaf is the substance ID of the substance (fresh) of Ginkgo biloba L. or Ginkgo biloba L. (Whole plant). */
    parentSubstanceId?: Metriport.fhir.Identifier[];
    /** The parent substance of the Herbal Drug, or Herbal preparation. */
    parentSubstanceName?: string[];
    /** The country where the plant material is harvested or the countries where the plasma is sourced from as laid down in accordance with the Plasma Master File. For “Plasma-derived substances” the attribute country of origin provides information about the countries used for the manufacturing of the Cryopoor plama or Crioprecipitate. */
    countryOfOrigin?: Metriport.fhir.CodeableConcept[];
    /** The place/region where the plant is harvested or the places/regions where the animal source material has its habitat. */
    geographicalLocation?: string[];
    /** Stage of life for animals, plants, insects and microorganisms. This information shall be provided only when the substance is significantly different in these stages (e.g. foetal bovine serum). */
    developmentStage?: Metriport.fhir.CodeableConcept;
    /** Many complex materials are fractions of parts of plants, animals, or minerals. Fraction elements are often necessary to define both Substances and Specified Group 1 Substances. For substances derived from Plants, fraction information will be captured at the Substance information level ( . Oils, Juices and Exudates). Additional information for Extracts, such as extraction solvent composition, will be captured at the Specified Substance Group 1 information level. For plasma-derived products fraction information will be captured at the Substance and the Specified Substance Group 1 levels. */
    fractionDescription?: Metriport.fhir.SubstanceSourceMaterialFractionDescription[];
    /** This subclause describes the organism which the substance is derived from. For vaccines, the parent organism shall be specified based on these subclause elements. As an example, full taxonomy will be described for the Substance Name: ., Leaf. */
    organism?: Metriport.fhir.SubstanceSourceMaterialOrganism;
    /** To do. */
    partDescription?: Metriport.fhir.SubstanceSourceMaterialPartDescription[];
}
