/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * Todo.
 */
export interface SubstancePolymer extends Metriport.fhir.BaseResource {
    resourceType: "SubstancePolymer";
    /** Todo. */
    class?: Metriport.fhir.CodeableConcept;
    /** Todo. */
    geometry?: Metriport.fhir.CodeableConcept;
    /** Todo. */
    copolymerConnectivity?: Metriport.fhir.CodeableConcept[];
    /** Todo. */
    modification?: string[];
    /** Todo. */
    monomerSet?: Metriport.fhir.SubstancePolymerMonomerSet[];
    /** Todo. */
    repeat?: Metriport.fhir.SubstancePolymerRepeat[];
}
