/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A code to indicate if the substance is actively used.
 */
export type SubstanceStatus = "active" | "inactive" | "entered-in-error";

export const SubstanceStatus = {
    Active: "active",
    Inactive: "inactive",
    EnteredInError: "entered-in-error",
} as const;
