/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the supply request.
 */
export type SupplyRequestStatus =
    | "draft"
    | "active"
    | "suspended"
    | "cancelled"
    | "completed"
    | "entered-in-error"
    | "unknown";

export const SupplyRequestStatus = {
    Draft: "draft",
    Active: "active",
    Suspended: "suspended",
    Cancelled: "cancelled",
    Completed: "completed",
    EnteredInError: "entered-in-error",
    Unknown: "unknown",
} as const;
