/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current state of this test report.
 */
export type TestReportStatus = "completed" | "in-progress" | "waiting" | "stopped" | "entered-in-error";

export const TestReportStatus = {
    Completed: "completed",
    InProgress: "in-progress",
    Waiting: "waiting",
    Stopped: "stopped",
    EnteredInError: "entered-in-error",
} as const;
