/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The result of this operation.
 */
export type TestReportOperationResult = "pass" | "skip" | "fail" | "warning" | "error";

export const TestReportOperationResult = {
    Pass: "pass",
    Skip: "skip",
    Fail: "fail",
    Warning: "warning",
    Error: "error",
} as const;
