/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The direction to use for the assertion.
 */
export type TestScriptAssertDirection = "response" | "request";

export const TestScriptAssertDirection = {
    Response: "response",
    Request: "request",
} as const;
