/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of this value set. Enables tracking the life-cycle of the content. The status of the value set applies to the value set definition (ValueSet.compose) and the associated ValueSet metadata. Expansions do not have a state.
 */
export type ValueSetStatus = "draft" | "active" | "retired" | "unknown";

export const ValueSetStatus = {
    Draft: "draft",
    Active: "active",
    Retired: "retired",
    Unknown: "unknown",
} as const;
