/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../..";

/**
 * An authorization for the provision of glasses and/or contact lenses to a patient.
 */
export interface VisionPrescriptionLensSpecification {
    /** Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces. */
    id?: string;
    /** May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. */
    extension?: Metriport.fhir.Extension[];
    /** May be used to represent additional information that is not part of the basic definition of the element and that modifies the understanding of the element in which it is contained and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions. Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself). */
    modifierExtension?: Metriport.fhir.Extension[];
    /** Identifies the type of vision correction product which is required for the patient. */
    product: Metriport.fhir.CodeableConcept;
    /** The eye for which the lens specification applies. */
    eye?: Metriport.fhir.VisionPrescriptionLensSpecificationEye;
    /** Lens power measured in dioptres (0.25 units). */
    sphere?: Metriport.fhir.Decimal;
    /** Power adjustment for astigmatism measured in dioptres (0.25 units). */
    cylinder?: Metriport.fhir.Decimal;
    /** Adjustment for astigmatism measured in integer degrees. */
    axis?: number;
    /** Allows for adjustment on two axis. */
    prism?: Metriport.fhir.VisionPrescriptionPrism[];
    /** Power adjustment for multifocal lenses measured in dioptres (0.25 units). */
    add?: Metriport.fhir.Decimal;
    /** Contact lens power measured in dioptres (0.25 units). */
    power?: Metriport.fhir.Decimal;
    /** Back curvature measured in millimetres. */
    backCurve?: Metriport.fhir.Decimal;
    /** Contact lens diameter measured in millimetres. */
    diameter?: Metriport.fhir.Decimal;
    /** The recommended maximum wear period for the lens. */
    duration?: Metriport.fhir.Quantity;
    /** Special color or pattern. */
    color?: string;
    /** Brand recommendations or restrictions. */
    brand?: string;
    /** Notes for special requirements such as coatings and lens materials. */
    note?: Metriport.fhir.Annotation[];
}
