/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Metriport } from "@fern-api/metriport";
import * as core from "../../../../core";

export const DownloadDocumentResponse: core.serialization.ObjectSchema<
    serializers.DownloadDocumentResponse.Raw,
    Metriport.DownloadDocumentResponse
> = core.serialization.object({
    url: core.serialization.string(),
});

export declare namespace DownloadDocumentResponse {
    interface Raw {
        url: string;
    }
}
