/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { Metriport } from "@fern-api/metriport";
import * as core from "../../../../core";

export const GetDocumentsResponse: core.serialization.ObjectSchema<
    serializers.GetDocumentsResponse.Raw,
    Metriport.GetDocumentsResponse
> = core.serialization.object({
    queryStatus: core.serialization.lazy(async () => (await import("../../..")).QueryStatus),
    documents: core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).Document)),
});

export declare namespace GetDocumentsResponse {
    interface Raw {
        queryStatus: serializers.QueryStatus.Raw;
        documents: serializers.Document.Raw[];
    }
}
