/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface MedicalRecordSummaryRequest {
    /**
     * The type of conversion to perform. `html` or `pdf`
     */
    conversionType: string;
}
