/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConsolidatedWebhookStatus = "completed" | "failed";

export const ConsolidatedWebhookStatus = {
    Completed: "completed",
    Failed: "failed",
} as const;
