/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../..";

export interface PayloadPatient {
    /** The ID of the patient. */
    patientId: string;
    /** The external ID of the patient. */
    externalId?: string;
    /** The status of the webhook. */
    status: Metriport.medical.ConsolidatedWebhookStatus;
    /** The FHIR bundle with the patient's consolidated data. */
    bundle?: Metriport.fhir.Bundle;
    /** The filters used to obtain the bundle. */
    filters?: Metriport.medical.Filters;
}
