/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../..";

export interface WebhookPatientConsolidatedDataPayload {
    /** The metadata of the webhook. */
    meta: Metriport.medical.WebhookMetadataPayload;
    /** An array of Payload Patient objects. */
    patients: Metriport.medical.PayloadPatient[];
}
