/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../..";

export interface WebhookDocumentDataPayload {
    /** The ID of the Document. */
    id: string;
    /** The file name of the document. */
    fileName: string;
    /** The description of the document. */
    description?: string;
    /** The MIME type of the document. */
    mimeType?: string;
    /** The size of the document in bytes. */
    size?: number;
    /** The URL of the document. */
    url?: string;
    /** The status of the document. */
    status?: string;
    /** The indexed date of the document in ISO-8601 format. */
    indexed?: string;
    /** The type of the document. */
    type?: Metriport.fhir.CodeableConcept;
}
