/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         patientId: "12345678"
 *     }
 */
export interface StartBulkGetDocumentUrlRequest {
    /**
     * The ID of the patient for which to initiate the bulk URL generation.
     */
    patientId: string;
}
