/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         patientId: "12345678",
 *         facilityId: "12345678",
 *         body: {
 *             "youCan": "putAny",
 *             "stringKeyValue": "pairsHere"
 *         }
 *     }
 */
export interface StartDocumentQueryRequest {
    /**
     * The ID of the Patient for which to list available Documents.
     */
    patientId: string;
    /**
     * The ID of the Facility where the patient is receiving care.
     */
    facilityId: string;
    /**
     * Metadata holds a record of up to 50 custom string key-value pairs. Key names can be up to 40 characters long and values up to 500 characters long.
     * This metadata will be returned in the webhook response.
     *
     */
    body?: Record<string, string>;
}
