/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../../..";

/**
 * @example
 *     {
 *         name: "Metriport Inc.",
 *         type: Metriport.medical.OrgType.Ambulatory,
 *         location: {
 *             addressLine1: "2261 Market Street",
 *             addressLine2: "#4818",
 *             city: "San Francisco",
 *             state: Metriport.UsState.Ca,
 *             zip: "94114",
 *             country: "USA"
 *         }
 *     }
 */
export interface OrganizationUpdateRequest {
    ETag?: string;
    /**
     * The name of your organization.
     * This is usually your legal corporate entity name -
     * for example `Metriport Inc.`.
     *
     */
    name: string;
    /** The type of your organization. */
    type: Metriport.medical.OrgType;
    location: Metriport.Address;
}
