/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         body: undefined
 *     }
 */
export interface GetPatientConsolidatedData {
    /**
     * A comma separated, case sensitive list of resources to be returned.
     * If none are provided all resources will be included.
     */
    resources?: string;
    /**
     * The start date (inclusive) for which to filter returned resources -
     * formatted `YYYY-MM-DD` as per ISO 8601. If not provided,
     * no start date filter will be applied.
     */
    dateFrom?: string;
    /**
     * The end date (inclusive) for which to filter returned resources -
     * formatted `YYYY-MM-DD` as per ISO 8601. If not provided,
     * no end date filter will be applied.
     */
    dateTo?: string;
    /**
     * The doc type to convert to. Either `html` or `pdf`.
     */
    conversionType?: string;
    /**
     * Metadata holds a record of up to 50 custom string key-value pairs. Key names can be up to 40 characters long and values up to 500 characters long.
     * This metadata will be returned in the webhook response.
     *
     */
    body?: Record<string, string>;
}
