/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GetDocumentsRequest {
    /**
     * Patient ID for which to retrieve document metadata
     */
    patientId: string;
    /**
     * The facility providing NPI for the document query
     */
    facilityId: string;
    forceQuery?: string;
}
