/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Metriport from "../../../../..";

export interface MedicalRecordStatus {
    /** The status of the html conversion */
    html: Metriport.medical.RecordStatus;
    /** The status of the pdf conversion */
    pdf: Metriport.medical.RecordStatus;
}
