/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RecordStatus {
    /** Whether or not the record exists */
    exists: boolean;
    /** The date the record was created */
    createdAt?: string;
}
