/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as core from "./core";
import { Document } from "./api/resources/document/client/Client";

export declare namespace MetriportClient {
    interface Options {
        environment: string;
        apiKey: core.Supplier<string>;
    }
}

export class MetriportClient {
    constructor(protected readonly options: MetriportClient.Options) {}

    protected _document: Document | undefined;

    public get document(): Document {
        return (this._document ??= new Document(this.options));
    }
}
