/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const MetriportEnvironment = {
    Production: "https://api.metriport.com",
    Sandbox: "https://api.sandbox.metriport.com",
} as const;

export type MetriportEnvironment = typeof MetriportEnvironment.Production | typeof MetriportEnvironment.Sandbox;
